### ISSUE TITLE
Docs - Salt version needed?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#10]
https://ocdsdeploy.readthedocs.io/en/latest/salt.html

Work out the minimum version of Salt required and document here for people who want to install a suitable version. Link to install pages for common operating systems.

**Comment by jpmckinney** [comment]
I think it's okay to specify "a" version. The absolute minimum version isn't necessary.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs - Salt version needed?](https://trello.com/c/S8W11gKG/78-docs-salt-version-needed)

**Comment by robredpath** [comment]
@odscjames what're the things that we need to consider here? Would a reasonable basis be to go for the version that's in the most recent Ubuntu LTS?

**Comment by jpmckinney** [comment]
For macOS, Homebrew has recent versions (2019.2.0 (Fluorine) presently).
