### ISSUE TITLE
Set environment variables for proxy URLs for ocdskfs user

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#101]
Currently they need to specify the server directly.

Suggestion from https://trello.com/c/QfFio5Jf/157-write-scrapers-for-new-paraguay-api : It would be nice if we can have an environment variable in kingfisher-process server for the proxy server's address, so we don't have to type it every time we need it.

**Comment by jpmckinney** [comment]
Pending discussion in https://github.com/open-contracting/kingfisher-scrape/issues/296, we might actually just set the `http_proxy` and `https_proxy` variables for the `ocdskfs` user after all.
