### ISSUE TITLE
"Deploy Kingfisher Process without losing Scrapy requests" in docs

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#103]
I'm not sure if this section is as useful as intended. 

https://ocdsdeploy.readthedocs.io/en/latest/how-to/kingfisher.html#deploy-kingfisher-process-without-losing-scrapy-requests

The problem is that while this technically won't lose current Scrapy crawls, it may still result in some data from those crawls not making it's way into the Kingfisher database. The problem is that if Scrapy can't contact the API, it currently won't retry or anything. https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/extensions.py#L100 So if the web server is in some way broken even briefly (say during a uWSGI reload), and in that time Scrapy tries to put information in the database, it will result in lost information. Worse, it will be hard to notice this without very carefully checking the logs of any crawls that are currently going on.

If this section stays, it should at least have a big warning about this.

This section is more useful for doing upgrades that take longer than you'd want to run through a salt session, like the collection_id one we expected to take several hours - but I think that's been the only one (and I made sure no-one was running a crawl at the time). We could add a note saying this is useful for those purposes.

I can do a pull request?

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document common sysadmin/devops activities so that OCP know what to expect from hosting services](https://trello.com/c/Ee5rrSA1/20-document-common-sysadmin-devops-activities-so-that-ocp-know-what-to-expect-from-hosting-services)

**Comment by jpmckinney** [comment]
No requests will be dropped during the uwsgi reload, as stated in those docs:

> service uwsgi reload runs /etc/init.d/uwsgi reload, which sends the SIGHUP signal to the master uWSGI process, which causes it to gracefully reload and not lose any requests from Scrapy. https://uwsgi-docs.readthedocs.io/en/latest/Management.html#reloading-the-server

**Comment by jpmckinney** [comment]
Closing, but can re-open if I misunderstood uWSGI's docs.

**Comment by jpmckinney** [comment]
I've added a note explaining that the how-to guide is only relevant if spiders are running.
