### ISSUE TITLE
Toucan has crontab that is not in Salt

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#104]
The ocdskit-web user has:

```
0 0 * * * find /home/ocdskit-web/ocdskit-web/media -mindepth 2 -mtime +1 -exec rm {} \;
0 0 * * * find /home/ocdskit-web/ocdskit-web/media -mindepth 1 -type d -print | xargs rmdir 2>/dev/null
```

I just now fixed the second line, which was previously:

```
0 0 * * * find /home/ocdskit-web/ocdskit-web/media/* -type d -print | xargs rmdir 2>/dev/null
```

which failed if the media directory was empty.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy - issues around ordering of salt actions](https://trello.com/c/vK4xH2Z6/228-deploy-issues-around-ordering-of-salt-actions)
