### ISSUE TITLE
Carry over any additional Prometheus alerts from ODS deployment

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#109]
It looks like we just have four to check that the blackbox reporter is up, the website is up, there's >=10% free disk space, and there's >=50MB memory remaining.

Is that all that ODS had in its Prometheus server? @robredpath 

I think the memory check should be higher or a percentage. 50MB is very close to swapping.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prometheus follow-up documentation and configuration](https://trello.com/c/PAZ3SMit/189-prometheus-follow-up-documentation-and-configuration)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prometheus follow-up documentation and configuration](https://trello.com/c/PAZ3SMit/189-prometheus-follow-up-documentation-and-configuration)

**Comment by jpmckinney** [comment]
Noting this is configured in `conf-prometheus-rules.yml`.

**Comment by odscjames** [comment]
> Is that all that ODS had in its Prometheus server?

Yes - we were still reviewing data we collected to decide what was useful to alert on. 

I like the point made in the Prometheus documentation - you should alert on things your users will directly notice when possible and not so much on background things that may or may not be a real alarm. Hence it would be interesting to see if we can do more direct reporting from inside applications like we started in Kingfisher process or more interesting things with the blackbox exporter. 

> I think the memory check should be higher or a percentage.

Sure, do you want to define that? you can run a graph of 

    node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes

to see historical values

**Comment by jpmckinney** [comment]
What do you mean by more interesting things with the blackbox exporter?

Standard search (1GB total) [peaks at 90% usage](https://monitor.prometheus.open-contracting.org/graph?g0.range_input=8w&g0.stacked=0&g0.expr=1%20-%20node_memory_MemAvailable_bytes%20%2F%20node_memory_MemTotal_bytes&g0.tab=0). Redash (2GB total) peaks at 70%. Others peak at 40% (at most).

A quick web search suggests people often set alerts for 80% or 90%. What do you think is an appropriate policy, @robredpath @odscjames?

If we go with 80%, I think the options are:

* Silence alerts: Use 80% usage (can also be expressed as 20% available) for all servers, and silence alerts about standard-search
* Two alerts: 95% for standard-search, 80% for others
* Mixed approach: 95% for standard-search, 80% for **all**, but silence 80% alerts about standard-search (don't silence 95% alerts)

I don't like option 1 as it won't alert when standard-search gets really bad. I don't like option 2, as it sets an inconsistent policy. So, I like option 3.

If we go with 90% instead of 80%, then we can just start with 90% for all, and postpone the second alert until we see that standard-search is alerting a lot. The decision on % should be a policy decision independent of current servers' memory usage.

**Comment by odscjames** [comment]
> What do you mean by more interesting things with the blackbox exporter?

Just wondering if there were other webpages we could monitor that would give us a indicator on whether our services were available or not (also applies to uptimerobot).

**Comment by odscjames** [comment]
I've put in an alert for 20% and 5% (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes comes out at the other end of the scale) for all servers (it's more robust if it just applies to all servers, and it doesn't hurt to have more memory alerts) and a silence for 20% on Standard Search.

**Comment by jpmckinney** [comment]
Great! I figure this issue is closed.

We can continue to think about alerts for things that users will notice and create issues as needed. 

To date, I think the main things users notice (besides the things for which we already have alerts) are the time it takes for background tasks to complete within Scrape, Process, Views. I guess we'd need to report the time it took to complete a task relative to the size of the input.

For other apps (Data Review Tool, Standard Search, Toucan), I suppose we can report the time it takes to prepare a response – but I think there are better tools for reporting the time from the browser's perspective, which would include network and rendering time.

**Comment by jpmckinney** [comment]
I created a new issue based on my last comment: https://github.com/open-contracting/deploy/issues/119
