### ISSUE TITLE
Process & Docs - Deploy Token Process

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#11]
https://ocdsdeploy.readthedocs.io/en/latest/deploying.html

 Work out how we’re going to make a deploy token work between Open Data Services and OCP, so that OCP staff can deploy. Document.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process & Docs - Deploy Token Process](https://trello.com/c/H8EUN4VK/77-process-docs-deploy-token-process)

**Comment by robredpath** [comment]
@odscjames @jpmckinney I'm just running through the various issues ahead of next week's call and this seems like one we might be able to get resolved ahead of time. 

At ODSC we have a wiki page in our Redmine install called the Badger Of Deploy. The procedure is that you edit the page to say that you have the Badger before you start working on servers, and then when you're done, you release the Badger. It's worked for us so far, and in practice it's rare that one person wants the Badger while another person has it, I think. 

Shall we do something similar for OCP?

In the longer term, I've got some ideas as to how we might improve this, but to me, I think this is sufficient for now. 

Thoughts?

**Comment by jpmckinney** [comment]
Sure, we can have a CRM wiki page for that – it'll error with an edit conflict in the unlikely scenario that two people decide to work on servers at the same time.

**Comment by jpmckinney** [comment]
Follow-up: Will document https://crm.open-contracting.org/projects/ocds/wiki/Deploy_token and add David Spencer (and Tim Williams if not already) to CRM.
