### ISSUE TITLE
Document any common Prometheus tasks

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#110]
Is it just a service that we leave alone like Uptime Robot, or is there something to do with it at some interval?

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prometheus follow-up documentation and configuration](https://trello.com/c/PAZ3SMit/189-prometheus-follow-up-documentation-and-configuration)

**Comment by odscjames** [comment]
There isn't any regular tasks.

There is the normal upgrade process on it's component's and servers like anything we host ourselves but nothing unusual.

Maybe one semi-regular/occasional task in to review data by hand and see if current alerts are working well.

**Comment by jpmckinney** [comment]
Sounds good. Upgrade is #108. I added a note to https://trello.com/c/vAbqECmA/194-being-responsible-for-ocp-servers-page-in-docs about checking the graphs at https://ocdsdeploy.readthedocs.io/en/latest/use/prometheus.html and checking the alerts.
