### ISSUE TITLE
Remove Blackbox Exporter

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#113]
UptimeRobot has more features and is easier to manage (just edit the alerts in a UI, rather than in a conf file). Do we need both? If yes, then we can add the missing alerts from UptimeRobot into `conf-prometheus.yml`.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prometheus follow-up documentation and configuration](https://trello.com/c/PAZ3SMit/189-prometheus-follow-up-documentation-and-configuration)

**Comment by jpmckinney** [comment]
If we need both, we can add this step to `create_server.rst`:

```rst

If the service is being introduced:

#. Add its target to the `Blackbox <https://github.com/prometheus/blackbox_exporter>`__ job in ``salt/private/prometheus-server-monitor/conf-prometheus.yml``
```

**Comment by jpmckinney** [comment]
If we were only using Prometheus, and if the its server were to go down, then we'd lose uptime monitoring for all services. So, we'd want UptimeRobot to at least monitor Prometheus.

Given that UptimeRobot has great availability, and it's unlikely that it will go down at the same time as our services, I think the question remains as to whether there's value in having Blackbox Exporter.

**Comment by odscjames** [comment]
It’s really up to how paranoid we want to be - do we want to cover the case that Prometheus goes down at exactly the same time one of our services goes down? Or the case that uptime robot goes down at exactly the same time one of our services goes down? 

If not it will not take long to remove one of them.

**Comment by jpmckinney** [comment]
I think it's more likely that Prometheus goes down at the same time (e.g. Bytemark goes down and Prometheus and most services go down). I'll rename the issue.

**Comment by odscjames** [comment]
Removed

**Comment by jpmckinney** [comment]
Removed in bc5e5c7125ad79957aedaed55d5d1b51252e487b
