### ISSUE TITLE
ocdskingfisherprocess: CREATE EXTENSION tablefunc;

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#117]
@kindly ran this on the ocdskingfisherprocess database for @duncandewhurst. I figure it should be in Salt.

**Comment by jpmckinney** [comment]
@duncandewhurst I see a few crosstabs named `tablefunc_crosstab_2`, etc. in the database. Are these in use? What are they?

**Comment by duncandewhurst** [comment]
I think those are added automatically by the tablefunc extension. See F.38.1.3. crosstabN(text) in the [tablefunc docs](https://www.postgresql.org/docs/current/tablefunc.html).

I asked @kindly to add the tablefunc extension as I wanted to generate some pivot tables. I don't think it's in active use now, but it would be good to keep it in case someone wants to do pivot tables again in the future.

**Comment by jpmckinney** [comment]
Are the pivot tables still around or have they been deleted?

**Comment by duncandewhurst** [comment]
They were just select queries, so they never existed in the database.

The queries still exist in an old notebook, but not one that's in active use.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ocdskingfisherprocess: CREATE EXTENSION tablefunc;](https://trello.com/c/kZDEibj7/260-ocdskingfisherprocess-create-extension-tablefunc)

**Comment by odscjames** [comment]
Now live and in master
