### ISSUE TITLE
Regular server maintenance

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#12]
Discuss if this will be the same or different in future. Document the procedure here more fully.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process & Docs - Regular Server Maintenance](https://trello.com/c/WZ8JlrZ6/76-process-docs-regular-server-maintenance)

**Comment by jpmckinney** [comment]
This is mainly package updates.

**Comment by jpmckinney** [comment]
This page only had "Open Data Services Coop currently do this weekly" so I'll remove it in an upcoming PR, until we have a PR that closes this issue.

**Comment by jpmckinney** [comment]
Rob wrote in an email that this includes:

* checking for (and applying) package updates
* running highstate to ensure that any shared deploy changes are applied
* reviewing monitoring and investigating anything that looks abnormal
* checking security notifications daily and applying updates if relevant
* checking hosting provider network status daily and checking for impact if relevant
* carrying out backups via the Bytemark control panel

**Comment by jpmckinney** [comment]
* checking for (and applying) package updates
  * Done: https://ocdsdeploy.readthedocs.io/en/latest/deploy/packages.html
* running highstate to ensure that any shared deploy changes are applied
  * I think OK to assume we applied changes to all servers at the time the changes were made
* reviewing monitoring and investigating anything that looks abnormal
  * I think OK to wait for alerts from Prometheus, and investigate when notified
* checking security notifications daily and applying updates if relevant
  * **Rob to send the mailing list to James M**
* checking hosting provider network status daily and checking for impact if relevant
  * **Rob to share hosting provider network status links**
* carrying out backups via the Bytemark control panel
  * These are scheduled automatically. They are configured on https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html
