### ISSUE TITLE
UptimeRobot throwing irregular small downtime alerts for Prometheus

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#121]
Is there any more data in uptimerobot you can share?

Any ideas?

**Comment by jpmckinney** [comment]
I have no idea. UptimeRobot user/pass is in LastPass.

**Comment by odscjames** [comment]
It's 2FA so I didn't want to bother you for that until I'd checked.

https://status.bytemark.org/issues/303

They could just be having very temporary network glitches if they feel the need to upgrade their network. That server is the only one in the Manchester data centre.

Maybe we just leave this a few weeks and see if it's resolved anyway - server seems fine whenever we check it manually.

**Comment by jpmckinney** [comment]
Ah, right, I forgot it was 2FA. I can remove that if more convenient.

I don't think there's a way to configure UptimeRobot to wait longer before alerting about failure (maybe on the Pro plan).

Closing if there's nothing we can do.

**Comment by odscjames** [comment]
Still happening. 

Had a quick look at logs, can't see anything of interest. Can I suggest putting the interval on the uptime check up? I'm guessing it's on 5 min check at moment, maybe an hour or longer?

**Comment by jpmckinney** [comment]
The interval controls how frequently UptimeRobot sends a request to check that the service is up. Once it's down, it checks every minute, and I see no way to control that.

**Comment by jpmckinney** [comment]
I changed it to an hour, but it will still incorrectly alert – just 12x less often on average.
