### ISSUE TITLE
Redash: Set up mail (for password resets, etc.)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#123]
https://redash.io/help/open-source/setup#Mail-Configuration

I'll have to create another Amazon SES user: https://github.com/open-contracting/deploy/issues/31#issuecomment-537034694

I can move that to a docs page, and include the sample justifications I sent to AWS.

**Comment by jpmckinney** [comment]
The same SMTP credentials as for Prometheus can be used. However, use the `noreply@noreply.open-contracting.org` email address instead. (We can change Prometheus to use this address as well. It's a lot of overhead to verify a domain and email address for every service.)

**Comment by odscjames** [comment]
Email done for Redash. Leaving open for Prometheus.
