### ISSUE TITLE
Use _common.conf for both HTTP and HTTPS

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#125]
After doing #124 I've left both 

* salt/apache/redash.conf
* salt/apache/redash.conf.include

In the repository.

I think previously in these cases you have removed the former, but can we leave it?

1)

When setting up a new server from scratch, you may need to set up the site with no HTTPS and then let the Lets Encrypt bot run it's verification process. (You might try to avoid this in some circumstances by copying /etc/letsencrypt/ from the old server to the new, but this is not always possible)

2)

When running a site locally on a VM for testing, you can't do the Lets Encrypt bot verification process. Thus it's important to set https to 'no' before installing to your local VM.

In both these cases, the non-include file is needed. Currently, the alternative is that people have to create them by hand when doing either of these tasks which is error prone and takes time.

**Comment by jpmckinney** [comment]
I think we can just make `_common.conf` smarter, so that it can be a common base for both branches of the if-statement in the apache macro. That way, whether you set HTTP or HTTPS, you'll always only have to edit an include file. I think the only HTTP service is Kingfisher Process.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use _common.conf for both HTTP and HTTPS](https://trello.com/c/LkmDc3Xy/259-use-commonconf-for-both-http-and-https)

**Comment by odscjames** [comment]
Done - all files are now .includes

Had to add ports argument to apache macro to cover case of Prometheus on Kingfisher server being on a non 80 / 443 port.

Tested by
* Kingfisher install on VM
* Kingfisher install on live server
* OCDS Docs Live install on live server, to make sure legacy site still worked and passing ports array as default works.
