### ISSUE TITLE
Server monitoring

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#13]
https://ocdsdeploy.readthedocs.io/en/latest/server-monitoring.html

Document how to fully set up the agent on each server so that others can do this. Document how to set up a server, or more likely, link to existing documentation.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs - Server Monitoring](https://trello.com/c/1fP0KA5X/75-docs-server-monitoring)

**Comment by jpmckinney** [comment]
This is now using Prometheus, whose configuration is in opendataservices-deploy. Once we setup an OCP server, we can document this further.

**Comment by odscjames** [comment]
In order that one Trello card currently in progress is not blocked by another one that has been not prioritised yet, can we make this issue just about documenting client setup and add to #31 that #31  should also include adding server documentation?

**Comment by jpmckinney** [comment]
@odscjames Yes, sounds good to me.
