### ISSUE TITLE
All servers crons should have MAILTO

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#132]
From @jpmckinney  in different discussion:

> We can also add a cron.env_present for MAILTO for all servers with cron jobs, as otherwise we need to login to check mail to see cron jobs' stderr / stdout. Some cron jobs especially in Kingfisher Process have very noisy output (though not as bad as they used to be), so that will need to be changed before we enable email.

**Comment by jpmckinney** [comment]
We have MAILTO for the root user (471c7253), but other users have cron jobs.

**Comment by jpmckinney** [comment]
I didn't add MAILTO for the cron jobs of the old version of Kingfisher Process, because it doesn't have code for catching warnings from OCDS Merge, and we intend to replace it anyhow: #402
