### ISSUE TITLE
Scrapyd isn't restarted on deploy

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#134]
I need to manually restart it: https://ocdsdeploy.readthedocs.io/en/latest/deploy/maintain.html#restart-services

**Comment by jpmckinney** [comment]
A nice side-effect is that crawls aren't interrupted. So, maybe we just need an additional instruction that if kingfisher-collect changed in a way not captured by `scrapyd-deploy`, then we need to restart the service?

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scrapyd isn't restarted on deploy](https://trello.com/c/IB665j1L/258-scrapyd-isnt-restarted-on-deploy)

**Comment by odscjames** [comment]
I would agree that the side effect is nice, so if this is the case just documenting this.

However, I read something that said Scrapy is meant to remember crawls across some actions - I tried to set this up at the time and didn't manage to get it working. (It wasn't a very high priority task at the time). Might be worth looking at again?

**Comment by jpmckinney** [comment]
This issue can just be about documentation. https://github.com/open-contracting/kingfisher-collect/issues/485 is the issue for looking into Scrapy job persistence.

**Comment by jpmckinney** [comment]
Closed by #185
