### ISSUE TITLE
Backup the Scrapyd logs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#135]
Follow-up from open-contracting/kingfisher-scrape#275

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hosted Kingfisher - Set up backups of Views and logs](https://trello.com/c/x4I2LFnh/218-hosted-kingfisher-set-up-backups-of-views-and-logs)

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backup the Scrapyd logs](https://trello.com/c/eRKimgTA/257-backup-the-scrapyd-logs)

**Comment by jpmckinney** [comment]
This will be closed as part of #153. I don't think we need backups beyond that.

**Comment by jpmckinney** [comment]
Done in Kingfisher Archive.
