### ISSUE TITLE
Clarify the Redash instructions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#138]
https://ocdsdeploy.readthedocs.io/en/latest/deploy/redash.html

I started clarifying the instructions in #137. Firstly, I made a copy of the `setup.sh` script, and made a few changes, so that it can simply be run as a file, instead of asking the user to figure out which parts to run manually. My understanding is that the changes are just:

1. Not running `install_docker`
1. Not running `create_directories` (though I don't see the harm)
1. Setting `COOKIE_SECRET` and `SECRET_KEY`
1. Making some substitutions and additions to `docker-compose.yml`
1. Not editing `~/.profile` (though I don't see the harm)
1. Not running `sudo docker-compose run --rm server create_db`

A few questions for the rest of the old docs:

> mkdir -p /opt/redash/postgres-data
> Once this is made, the user permissions on it must not be changed. So it is in here, and not a salt instruction.

How are the permissions set? I see `drwx------ 19   70   70      4096 Apr  9 15:14 postgres-data/` on the server, but I don't see where those permissions/owner/group are set.

> Dump the Postgres database on the old server

Using what command, specifically? Can you give an example of a command that will work on the current server? It's not as obvious when the DB is in a container.

> Now for any upgrades run docker-compose run --rm server create_db

Isn't `docker-compose run --rm server manage db upgrade` for upgrades?

**Comment by odscjames** [comment]
> Firstly, I made a copy of the setup.sh script, and made a few changes, so that it can simply be run as a file, instead of asking the user to figure out which parts to run manually

So the reason I didn't do this is because I didn't want to get in a situation where the upstream instructions changed and our copied instructions got out of date enough that it became a problem. I'm hoping it will be a year or more before anyone has to do that process again, by which point who knows, maybe they will even have moved on to Ferble, the Docker successor that will be announced next week. Being silly, but I was aware we were in this situation with the previous non-Docker install and it could potentially be a problem. I thought it was better if the person had to check instructions upstream themselves and could then work out any future changes.

> How are the permissions set? I see drwx------ 19 70 70 4096 Apr 9 15:14 postgres-data/ on the server, but I don't see where those permissions/owner/group are set.

The Postgres Docker container sets them, so there is no need for us to do any steps there.

> Using what command, specifically? Can you give an example of a command that will work on the current server? It's not as obvious when the DB is in a container.

It's the usual command for pg_dump and restore, which is why I didn't document it. 
The only complexity is you have to open up the port from the outside world into the database docker container, which I tried to cover in the steps already there. After that it's a normal postgres connection.
But we can add the pg_dump command to be clear, if wanted.

>     Now for any upgrades run docker-compose run --rm server create_db
> Isn't docker-compose run --rm server manage db upgrade for upgrades?

Oh yes, sorry.

**Comment by jpmckinney** [comment]
Thanks, I added a section to document how we changed the script (3e74fed), with explanations for *why* we changed the script, so that a future user can make similar changes to future scripts. (The old docs referred to specific functions in the present Redash setup script, which might disappear in future scripts, so a future user might be completely lost as to what commands were run in the past to install Redash. Having a local copy of the script at least serves as a reference to compare against.)

> > ```
> > Now for any upgrades run docker-compose run --rm server create_db
> > ```
> >
> > Isn't docker-compose run --rm server manage db upgrade for upgrades?
>
> Oh yes, sorry.

Per the old instructions, this command will be run while the service is up. Shouldn't we first run `docker-compose stop server scheduler scheduled_worker adhoc_worker` as in Redash's [upgrade docs](https://redash.io/help/open-source/admin-guide/how-to-upgrade)?

> It's the usual command for pg_dump and restore, which is why I didn't document it.

Can you share the specific commands in this issue and I'll add them to the PR? Both commands take a variety of flags, so I'd rather be perfectly clear.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need to overhaul Redash Install process](https://trello.com/c/CvjzaiJg/111-need-to-overhaul-redash-install-process)

**Comment by odscjames** [comment]
> In old instructions, this command was run while the service is up. Shouldn't we first run docker-compose stop server scheduler scheduled_worker adhoc_worker as in Redash's upgrade docs?

Actually, the proper fix is the instruction to run ``docker-compose up -d`` is in the wrong place at step 5. At that point, you only need to start the server container. (``docker-compose up -d postgres`` or something? Not tested.) The other containers then aren't running, so don't need to be halted. ``docker-compose up -d`` should instead be run right after``docker-compose run --rm server manage db upgrade``. 

I think in this case it's good to be pedantic as running the app containers before you import the database might mean they try and do stuff to the database and then your import potentially becomes harder.

**Comment by odscjames** [comment]
> Can you share the specific commands in this issue and I'll add them to the PR? Both commands take a variety of flags, so I'd rather be perfectly clear.

The command to restore is still in bash history

    psql -h localhost -U postgres postgres -f redash.sql

I think this would then prompt you for password, which is in the env file.

pg_dump was run on a server that is now gone, but I think it was just:

    pg_dump -h localhost -U postgres postgres  -f redash.sql

I believe use of -f and not pipes is important so any character encoding issues are ok.

(All the meetings shortly so don't have time to test this or previous comment now.)

**Comment by jpmckinney** [comment]
Thanks – being "pedantic" is always good in cases like this (infrequent operations on software that few staff are expert in). We corrected several errors that way (incorrect upgrade command, incorrect commands order, etc.).

Closed by #137
