### ISSUE TITLE
Could not deploy kingfisher

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#139]
- Rendering SLS 'base:ocdskingfishercollect' failed: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'ocdskingfishercollect'

**Comment by odscjames** [comment]
@jpmckinney Can you check the fix in the linked commit is what you would expect?

**Comment by jpmckinney** [comment]
Yup! I might not have pushed the repo from the sub directory.
