### ISSUE TITLE
Process & Docs - making changes to Salt scripts

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#14]
https://ocdsdeploy.readthedocs.io/en/latest/making-changes.html

Discuss testing against a virtual machine or making changes against live servers. Discuss procedures for people who can not deploy for whatever reason to make changes (eg always via pull request?). Have clearer guidelines about when it is and is not appropriate to commit straight to master. Document.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process & Docs - making changes to Salt scripts](https://trello.com/c/Nw18TrKa/74-process-docs-making-changes-to-salt-scripts)

**Comment by odscjames** [comment]
Write up considerations:

how big change is, how "live" machine is, how easy to test on VM

Some specific cases:

apache config for docs site can be testing on "testing" virtual host, so on live server is fine.

**Comment by jpmckinney** [comment]
how 'live' machine is ~= importance of the service (e.g. don't want to bring down standard docs, but okay if Kingfisher temporarily down). An example of something that is not as easy to test on VMs are SSL configurations.
