### ISSUE TITLE
Move Deploy token

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#141]
As we add more organizations with access to deploy services, it makes less sense to use the CRM to host the deploy token page (CRM is for managing helpdesk analysts' work, time-tracking software developers' work, and to a much lesser extent planning software development).

Shall we move it to a Google document?

cc @JimACarter

**Comment by odscjames** [comment]
I'm not fussed about the token, but I'd like this to be considered alongside the issue of how all people with deploy access communicate. Previously we could use the CRM as a communications channel that would get all parties, if that's not going to be true in the future can we make sure something else is put in place?

**Comment by jpmckinney** [comment]
I've updated the deploy docs, and the deploy token is now in [Google Docs](https://docs.google.com/document/d/1kW2hI1PYYd8KC5QDyys8clPvshBMUZuLpEOO-DvSxqk/edit). The old wiki page links to it.

For communication between parties, OCP can create a Google Apps mailing list to which we subscribe sysadmin@open-contracting.org, sysadmin@dogsbody.com and code@opendataservices.coop (or whichever addresses you prefer). How's that?

**Comment by odscjames** [comment]
Personally I'm happy with that.

**Comment by jpmckinney** [comment]
@robredpath @JimACarter: Please let me know your teams' preferences.

**Comment by JimACarter** [comment]
We're happy with that, sysadmin@dogsbody.com's the best address to use

**Comment by jpmckinney** [comment]
I've created a Google Group and invited the above addresses, substituting James B and Rob's addresses for code@.

**Comment by jpmckinney** [comment]
This list is now mentioned at https://ocdsdeploy.readthedocs.io/en/latest/deploy/maintain.html
