### ISSUE TITLE
kingfisher-process: Consider adding a separate disk for the WAL

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#147]
https://wiki.postgresql.org/wiki/Slow_Query_Questions

**Comment by RobHooper** [comment]
I investigated this as part of #168 and decided against it. 
The big con using a separate disk is that we loose usable disk space.

If read requests are blocking write requests, then they should be querying the new read-only endpoint (kingfisher-replica1)

**Comment by jpmckinney** [comment]
Agreed, replica serves as an alternative solution.
