### ISSUE TITLE
Use avail bytes instead of free bytes for disk space alerts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#149]
~~The RootFileSystemLow alert uses node_filesystem_avail_bytes. node_filesystem_free_bytes includes the space reserved for the root user (5%).~~

~~If we're setting the alert's threshold with that in mind, then I think it's fine, though we might want to use the same metrics for both alerts, to avoid confusion.~~

**Comment by JimACarter** [comment]
I believe both alerts are currently using node_filesystem_free_bytes.  I'd be happy to swap to node_filesystem_avail_bytes and shift the alert thresholds by 5%.

**Comment by jpmckinney** [comment]
Oops, I was comparing to a saved query I use for Prometheus graphs.

In any case, I prefer node_filesystem_avail_bytes since it's easier to reason about it (otherwise I need to remember that the real space available to applications is 5% less).

**Comment by JimACarter** [comment]
Agreed, that makes sense, I'll update these when I deploy the new alerts for #133
