### ISSUE TITLE
Process & Docs - making changes to non-salt scripts  (eg. scripts used by Travis)

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#15]
https://ocdsdeploy.readthedocs.io/en/latest/making-changes.html

Discuss procedures and document such that all staff can make changes to these.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process & Docs - making changes to non-salt scripts (eg. scripts used by Travis)](https://trello.com/c/8Eg6sOJF/73-process-docs-making-changes-to-non-salt-scripts-eg-scripts-used-by-travis)

**Comment by odscjames** [comment]
Think this is just https://github.com/open-contracting/deploy/blob/master/deploy-docs.sh now

**Comment by jpmckinney** [comment]
I can add a bit of content based on recent experience.
