### ISSUE TITLE
Kingfisher-process restart rsyslog using salt service 

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#165]
In ocdskingfisherprocess.sls we are currently restarting rsyslog with cmd.run after uploading new configs.
It would be better if this used the salt service function and watched both config files to restart on change. 

https://github.com/open-contracting/deploy/blob/5f77ff11ae50ef634a25916c6c788070f64117dd/salt/ocdskingfisherprocess.sls#L171-L176

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher-process restart rsyslog using salt service](https://trello.com/c/9qy8YutW/269-kingfisher-process-restart-rsyslog-using-salt-service)

**Comment by jpmckinney** [comment]
Inspiration: https://github.com/saltstack-formulas/rsyslog-formula/blob/master/rsyslog/init.sls
