### ISSUE TITLE
postgres status checking during deployments

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#166]
You can easily deploy a bad postgres configuration because salt checks `systemctl status postgres` which shows the postgres service as running even if `pg_lsclusters` shows it is actually down. 

We hope that any issues will be picked up in testing, but it would be better if salt checked and alerted users that something is wrong when the deployment happens.

**Comment by jpmckinney** [comment]
If we add a state that fails if `pg_lsclusters` says it's down, then maybe we can have it `- require: - service: postgresql`, to ensure it runs after?

**Comment by jpmckinney** [comment]
@RobHooper Can you report this issue to SaltStack? I figure other users would like a fix.
