### ISSUE TITLE
Kingfisher Views PYC files got messed up

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#173]
Analysts reported "Magic Number" errors

https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error

Deleting PYC files did indeed fix it but the real question is how they got bad in the first place. Opening this issue to track future cases, if any, and try and work out why.

**Comment by jpmckinney** [comment]
Since this issue will remain open forever if there are no future cases, I prefer to close, and instead try to diagnose the issue the next time it happens. There are many magic numbers in Python and third-party packages, so this is impossible to debug without a backtrace.

**Comment by odscjames** [comment]
Just did a normal deploy and it works fine after, so that's good at least.
