### ISSUE TITLE
Consider switching to nginx

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#179]
We use Apache because it's what ODS had set up. Personally, I've been using nginx for longer, and it continues to grow in popularity. We should of course check that all Apache modules/features are replicated in nginx.

This is low priority as it won't yield significant changes in performance.

**Comment by Bjwebb** [comment]
We make heavy use of mod_rewrite for the version/language switcher, which is likely to be the hardest thing to replicate with nginx.
(Although, its opaque enough that maybe it should be replaced by a Python app anyway).

https://github.com/open-contracting/deploy/blob/64a0dde1c3954db561e8a6a41e242997a2ca9663/salt/apache/ocds-docs-live.conf.include#L94-L111

**Comment by jpmckinney** [comment]
Yeah, for the docs it's probably not worth the effort to switch. For apps, I think it's fairly straight-forward – but then we're using two web servers instead of one.

**Comment by jpmckinney** [comment]
Closing as not worth the effort at the moment.
