### ISSUE TITLE
Other profiles have staging banner

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#18]
https://standard.open-contracting.org/profiles/eu/master/en/
https://standard.open-contracting.org/profiles/gpa/master/en/

Is this because they are on `master`? Can we make an exception?

**Comment by jpmckinney** [comment]
I think the issue is that I'd have to [copy the profiles to the live server](https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/technical/deployment/#copy-the-schema-extension-and-extension-zip-file-into-place). However, these two profiles change frequently, and I don't want to have to run manual commands just to eliminate a banner.

**Comment by odscjames** [comment]
We already have some different types of banners served, https://github.com/open-contracting/deploy/blob/master/salt/apache/ocds-docs-staging.conf.include#L59 so we could add a special banner that is just empty for those 2 dirs. 

However, having "staging" actually serve live traffic is an oddity that might trip us or others up later. 

> these two profiles change frequently, and I don't want to have to run manual commands in order to publish the latest version

Is this a good opportunity to script some of that instead?

**Comment by jpmckinney** [comment]
I prefer to add a banner, where instead of providing a link to OCDS documentation, it mentions that, "The profile is in development and subject to change." Once we have a stable release, we can copy it to live, and we can change the banner along the lines of the PPP banner. How's that?

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Banner on EU and GPA Profiles](https://trello.com/c/eUEqLXVk/92-add-banner-on-eu-and-gpa-profiles)
