### ISSUE TITLE
Consolidate docs servers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#183]
I think we can run standard-search on the same server as the docs, given that no other service uses standard-search.

We can also remove the staging server, and instead have a staging directory. I don't really see the point in two VPSes.

**Comment by Bjwebb** [comment]
The original reason for two VPSes was for maximum isolation between the live server, and the server that Travis has login details to. However, we've not had any security issues with that Travis login, so merging the 2 makes sense (and we can still use user accounts to restrict permissions).

**Comment by jpmckinney** [comment]
@Bjwebb Thanks for the background. We use GitHub Actions now, but the idea is the same: only people with collaborator access to the repo can use the secrets to deploy. Looking at the main attack vectors:

* Compromise private SSH keys to push commits using git
  * I think this is low risk.
  * Note: Some of those SSH keys also have root access to the docs servers.
* Compromise GitHub password to make commits on GitHub.com
  * 2FA is required, so this is low risk.
* Compromise GitHub.com itself
  * I think this is low risk.

**Comment by Bjwebb** [comment]
I think I was also concerned about accidentally outputting the CI secrets in the build log. However, unlike Travis, GitHub Actions doesn't make the whole build log public.

**Comment by jpmckinney** [comment]
Finding references to development builds of OCDS documentation:

    standard.open-contracting.org/(?![>)"\\ ]|(?:staging|latest|schema|profiles|infrastructure|legacy|review|robots\.txt|1\.[01]|examples|\{\{version\}\})[/\]>)'])

**Comment by jpmckinney** [comment]
Closed by f6c445fd904335658d1d82672bda933a2bf905fb

Need to update `ci.yml` in documentation repos. Standard handbook updated.
