### ISSUE TITLE
Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#19]
Invalid HTTP_HOST header: '46.43.2.235'. You may need to add '46.43.2.235' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '46.43.2.235:443'. You may need to add '46.43.2.235' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'live.standard-search.opencontracting.uk0.bigv.io'. You may need to add 'live.standard-search.opencontracting.uk0.bigv.io' to ALLOWED_HOSTS.

Let's add these to the allowed hosts (the IP is for the standard-search server).

**Comment by odscjames** [comment]
> Invalid HTTP_HOST header: '46.43.2.235'. You may need to add '46.43.2.235' to ALLOWED_HOSTS.
> Invalid HTTP_HOST header: '46.43.2.235:443'. You may need to add '46.43.2.235' to ALLOWED_HOSTS.

Is there a use case for this one? Currently I think the only reason we would see this is bots trying to crawl us. (In fact, on a lot of our servers we set up an default apache placeholder site for bots to see).

> Invalid HTTP_HOST header: 'live.standard-search.opencontracting.uk0.bigv.io'. You may need to add 'live.standard-search.opencontracting.uk0.bigv.io' to ALLOWED_HOSTS.

www.live.standard-search.opencontracting.uk0.bigv.io is however already set up as an ALLOWED_HOSTS and an SSL cert name - for the same avoiding-bots reason as above, can we leave it as this?

**Comment by jpmckinney** [comment]
Aha. Is there a way to quiet specific HTTP_HOST errors, so that we don't continually get new reports in Sentry?

**Comment by odscjames** [comment]
I see the problem - we do have an default host in place for HTTP crawlers, but not for HTTPS crawlers - ie h t t p://46.43.2.235/ gets placeholder, h  t t p s://46.43.2.235/ gets site and generates a sentry error.

We can look into that.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Look into stopping HTTPS crawlers hitting real sites and generating errors](https://trello.com/c/tdbyqzFV/93-look-into-stopping-https-crawlers-hitting-real-sites-and-generating-errors)

**Comment by jpmckinney** [comment]
This has been solved in a few different ways:

* [Re-configure the DisallowedHost logger](https://github.com/readthedocs/readthedocs.org/pull/4879/files)
* [Ignore the DisallowedHost logger in Sentry's configuration](https://github.com/mozilla/kitsune/pull/3485/files)
* [Ignore the Sentry issues](https://github.com/mozilla/normandy/issues/1687)

For now I ignored them until [2038-01-19 03:14](https://en.wikipedia.org/wiki/Year_2038_problem). in Sentry.

**Comment by jpmckinney** [comment]
Also occurs on Data Review Tool (and presumably any Django app with Sentry installed).

**Comment by odscjames** [comment]
Commented in our deploy repository in https://github.com/OpenDataServices/opendataservices-deploy/issues/88

**Comment by jpmckinney** [comment]
I'm reconfiguring loggers.

* [x] toucan
* [ ] cove-ocds
* [ ] cove-oc4ids

**Comment by jpmckinney** [comment]
Done and deployed. There's an open PR for standard-search. Once closed, we can resolve the open issues in Sentry.

**Comment by Bjwebb** [comment]
PR for standard-search is merged now.

Looks to me like all the open issues in Sentry are gone already.
