### ISSUE TITLE
Changes to prometheus-server.service not loaded in

### ISSUE THREAD

**Issue by JimACarter** [open-contracting/deploy#192]
When deploying https://github.com/open-contracting/deploy/commit/e1444c99f429fe72c1e7a55eafa5a3069cdb59e7 I found that the change to prometheus-server.service was not loaded in.  To work around this I logged in and restarted the service by hand.
Prometheus was only reloaded https://github.com/open-contracting/deploy/blob/e1444c99f429fe72c1e7a55eafa5a3069cdb59e7/salt/prometheus-server-monitor.sls#L78
Ideally I'd like Prometheus to be restarted for changes to prometheus-server.service and reloaded for changes to conf-prometheus*.yml.  It would be simpler to restart for any of these changes though.

**Comment by jpmckinney** [comment]
Also done in 783f11e2c3757b1dba269ae1ea442c2f9924c60d

**Comment by jpmckinney** [comment]
Restored reloading for configuration files in 1163993f91191f51be5b80eca7df46d8628fa4a0
