### ISSUE TITLE
Should OpenDataServices/opendatacomparison-archive be migrated to this organisation?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#203]
Referenced in https://github.com/open-contracting/deploy/blob/94b9d53c77224ea31f681139002ac986050f78d9/salt/docs-legacy.sls#L9

**Comment by jpmckinney** [comment]
Sure, Ben and Rob are owners and can move it.

**Comment by jpmckinney** [comment]
Closed by 4409de3
