### ISSUE TITLE
Consider `set -euo pipefail` on some maintenance scripts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#204]
* [ ] check_update.sh
* [ ] rkhunter-check.sh
* [ ] sensors_check.sh

https://ocp-software-handbook.readthedocs.io/en/latest/shell/index.html#shell-options

**Comment by RobHooper** [comment]
:+1:  I agree, this is a good win.

Just noting that `set -o pipefail` will only work in `bash` scripts not `sh`.
I don't think we have any shell scripts but worth keeping in mind.

**Comment by jpmckinney** [comment]
Looks like sensor_check is sh, but we can change it to bash.

**Comment by jpmckinney** [comment]
Sounds good. I've approved the PR. (For some reason I did not get notified of the PR. I seem to be missing some GitHub notifications in general, and they are not going to spam...)

**Comment by RobHooper** [comment]
@jpmckinney it was in a different Git repo? might be worth checking you're subscribed to notifications there.
I wasn't 100% sure if you wanted to review changes in the maintenance repo the same way you manage the main deploy repo?

Also, happy we've addressed this Git issue - resolving.

**Comment by jpmckinney** [comment]
It seems when GitHub soft-launched their changes to security alerts, that many of my repos changed from watching all activities to *only* watching for security alerts 😞 . I've fixed it now.
