### ISSUE TITLE
hardware_sensors: Possible typo

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#209]
The condition uses `nct6775` but the filename is `nct6779`. Is that intended?

https://github.com/open-contracting/dogsbody-maintenance/blob/4b953dc3302249eb08ae11621ac52fada897c628/hardware_sensors/init.sls#L14-L28

**Comment by RobHooper** [comment]
This is because we have the `nct6779` sensor on replica1 but it requires the module `nct6775` to be loaded to interact with.
I imagine they're part of the same "family" and are API compatible with each other. 

Perhaps needs some comments in the code covering this?

**Comment by jpmckinney** [comment]
Thanks - I've added a comment.
