### ISSUE TITLE
postgres_monitoring: Unused REPLICATION_ERR variable

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#210]

**Comment by RobHooper** [comment]
@jpmckinney Please can you provide some more info regarding this, where are you seeing this message?

**Comment by jpmckinney** [comment]
It's not a message. There is simply a REPLICATION_ERR variable that is not used in the code. Is there any point in keeping it?

**Comment by RobHooper** [comment]
Ah I see, https://github.com/open-contracting/dogsbody-maintenance/blob/master/postgres_monitoring/files/replica_monitoring.sh#L27

Yes that variable is fine to remove. I expect we used to email out the report file but have since swapped it to the raw replica query.
