### ISSUE TITLE
David R from opendataservices added to kingfisher server access.

### ISSUE THREAD

**Issue by kindly** [open-contracting/deploy#217]
My public key is

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+rgZoWRzVmlQ0BsFnuuDySoz93aLnL4K/ngS+/jFOG07oalnadwk6haKbK68zzyqcpgC4EqHUweB7IG9NpSG/fI/K6GyIotXWCejFLjZO+D32mEI+jT66q4AHu8SNhLJYV4NSVafqISFZoGeZfZKGI1gISrz0GAKsnqQ1dGb7zWWiHo6SQtPf2awRhlNoCaah/WoGKduDEFhTeLeCnXEkwnETd+1WrnRWMZsYVEILX7rRM35/OlNVKv11wxdrOB9LwnEsJGwGnG85NEAMUmX+pEQSuRmXGXlAwFBCKQxENRL9Eb6eVQeGXjpg17/wTDbiOXvwbql3/CFcAr0/mQGFhCiWqIQ58B0P8w6EknonZAkasaGukw2NjU3/I10xmHBNgPRdvYxwvQn6P+/QOGCdm63QKIn2FhY3Fv15m3qD4HZ3VT1mA7JMv4SW5qyXcWIdgvGroht3Cg+Ae0u7a575PUiVv9Y4U/t8QOQdtd+I37J+hCJyvMUXbvxVF8e6rqQ68EgvMi+z9qp3LmBHfF4rQ50oTvN7e09ncqmRwEuOFv0jTCOwnmk9UIFFgSWx4Gcj1bZdv6rLFXvTJzodvW4tYhu0lDkF65AZxqpNYMTxJvc45WnUIqgVDThdMLqVtHMDWlkxtUhjyERyWA+2x+Mhk3JMZPwWeELvA/yVC3zNFw== david@david-ThinkPad-X250

**Comment by jpmckinney** [comment]
Done in a999905 and deployed.

**Comment by jpmckinney** [comment]
However, I want to monitor Salt's output on that server related to other changes, so I'm going to deploy now.
