### ISSUE TITLE
Consider Salt Minions instead of Agentless Salt

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#221]
Agentless Salt is fine for now. This issue documents some advantages to Salt Minions.

* Don't need to hardcode IPs
  * Main PostgreSQL server opens port to replica server
  * Prometheus clients open port to Prometheus server
  * Data Review Tools trust documentation server
  * Tinyproxy allows connections from Kingfisher server
* Don't need to store x509 keys and certificates
  * Prometheus clients use the same key, and the Prometheus server needs to know its PEM. With Salt Minions, the [x509](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html) state functions can set up unique keys for clients.

**Comment by RobHooper** [comment]
If we move to Salt Minions we could start using more advanced target groups as mentioned in https://github.com/open-contracting/deploy/issues/157#issuecomment-734854134

**Comment by jpmckinney** [comment]
Closing as we haven't accumulated many more reasons to switch to Salt Minions. Eliminating 4 hardcodings doesn't seem worth the effort (3 if we set up Data Review Tools at subdomains #266 #145).
