### ISSUE TITLE
Consider setting limits to /var/log/journal

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#233]
For example, It's taking up 2.4GB on the docs server (10%).

We can set `SystemMaxUse=` https://www.freedesktop.org/software/systemd/man/journald.conf.html

After doing that, we can run `journalctl --vacuum-size=` once.

**Comment by RobHooper** [comment]
We have seen multiple disk space alerts on the live.docs server since January. 
I have manually set `SystemMaxUse` on this server to help prevent the alerts, I will create a PR to formalise this soon.
