### ISSUE TITLE
Create extensions pg_trgm fuzzystrmatch on kingfisherprocess database including readonly database 

### ISSUE THREAD

**Issue by kindly** [open-contracting/deploy#237]
Would like to run

```sql
create extension fuzzystrmatch;
create extension pg_trgm;
```
on kingfisher databases.  Not sure this is replicated automatically so may need to be run on replica too.

This can not be done as a normal migration script as they need to be run as superuser.  So deploy repo seemed the correct place for it?

This would be useful for analyses purposes in order to do some basic deduplication/fuzzy matching.

**Comment by jpmckinney** [comment]
Sure, could you say a bit more about the need/use case?

**Comment by jpmckinney** [comment]
We presently add extensions like here: https://github.com/open-contracting/deploy/blob/master/salt/kingfisher/process/init.sls#L59-L65

**Comment by kindly** [comment]
I am doing some Red Flag analysis and some [criteria](https://docs.google.com/spreadsheets/d/12PFkUlQH09jQvcnORjcbh9-8d-NnIuk4mAQwdGiXeSM/edit#gid=0&range=D91) needs to see if some fields are similar (eg supplier addresses).

This could be done in pandas in colab but the memory requirements are likely too high.  The above extension give some options directly in the database.

**Comment by jpmckinney** [comment]
Done in 137c3fd

Let me know if it's not available on the replica (could sometimes take a little time)
