### ISSUE TITLE
Kingfisher - there is a failed state due to View changes

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#24]
https://github.com/open-contracting/kingfisher-views/pull/32/files removes requirements.txt

This unfortunately means we have a failed state:

> 
> ----------
>           ID: /home/ocdskfp/ocdskingfisherviews/.ve/
>     Function: virtualenv.managed
>       Result: False
>      Comment: An exception occurred in this state: Traceback (most recent call last):
>                ..............
>               FileNotFoundError: [Errno 2] No such file or directory: '/home/ocdskfp/ocdskingfisherviews/requirements.txt'
>      Started: 09:53:07.347843
>     Duration: 369.936 ms
>      Changes:

**Comment by jpmckinney** [comment]
Hmm, I didn't suspect that Process deployed the master branch of Views, since master branches in our setup are development branches…

Anyhow, the deployment can be somewhat simplified by `pip install -e git+https://github.com/open-contracting/kingfisher-views.git#egg=ocdskingfisherviews`

And then instead of changing into its directory, `ocdskingfisher-views-cli` will simply be available as a command-line tool from any directory.

**Comment by odscjames** [comment]
> since master branches in our setup are development branches…

For scrape, process and views we don't have any versioning process at present tho, so it's not a "dev" branch. It's more a continuous deployment type thing - as soon as something is merged to master, it should be considered deployable. Happy to discuss that, tho a new issue would be good, let's keep this issue on track.

I'll tag @kindly to comment on method of installation, we'll chat.

**Comment by odscjames** [comment]
Have chatted. Personally because you have to change into the directory to activate the virtual environment anyway it never bothered me that the command only works from one place (and I think we definitely want to keep a virtual env) - but happy to try an option that allows running from any directory.

**Comment by jpmckinney** [comment]
I think if it's installed with setup.py then it will be available from any directory – once the virtualenv is activated.

Whether we install via setup.py  or requirements.txt is the discussion in https://github.com/open-contracting/lib-cove-ocds/pull/28#issuecomment-533618374

If we end up installing with requirements.txt, then we can just have the command run from one place.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by odscjames** [comment]
The original problem that prompted this ticket has been fixed and deploys are fine.

Is there anything that has come out of this discussion you want to pick up as distinct tasks to look at? I think because views doesn't have a setup.py there isn't at the moment, and https://github.com/open-contracting/kingfisher/issues/329 might change how it's installed anyway.

> For scrape, process and views we don't have any versioning process at present tho, so it's not a "dev" branch. It's more a continuous deployment type thing - as soon as something is merged to master, it should be considered deployable.

Should this be documented somewhere, the Sphinx docs for each repo maybe, or the standards handbook?

**Comment by jpmckinney** [comment]
I made this PR: https://github.com/open-contracting/standard-development-handbook/pull/222/files

**Comment by odscjames** [comment]
Now that's merged, I think this can be closed?
