### ISSUE TITLE
covid19: Missing configuration of .env file

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#245]
* [x] The database user isn't configured, causing `python manage.py migrate` to fail. See https://ocdsdeploy.readthedocs.io/en/latest/maintain/databases.html#add-a-user
* [x] `.env` files seem to be missing. These can be configured in Salt by using `contents_pillar:` (search for examples in this repository).
    * `/home/covid19admin/covid19admin/.ve/lib/python3.6/site-packages/environ/environ.py:630: UserWarning: /home/covid19admin/covid19admin/covidadmin/.env doesn't exist - if you're not configuring your environment separately, create one.`

**Comment by bikramtuladhar** [comment]
we are not using `.env` file, instead we used export variable with `env` option in salt. There was missing private pillar for covid19 that's why these command failed. I have added private covid19 pillar and soon will send PR request.

**Comment by jpmckinney** [comment]
Great, we can close once https://github.com/open-contracting/deploy-pillar-private is updated, and after testing that the above Salt states succeed.

**Comment by jpmckinney** [comment]
Re-opening this issue since the .env file is in fact being used, and therefore needs to be tracked in Salt.

**Comment by jpmckinney** [comment]
`.env` file done in https://github.com/open-contracting/deploy/commit/419244cf65f266a688e3e51c09b58252fd42d78a as part of #249
