### ISSUE TITLE
Kingfisher-process reduce app logs into syslog

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#250]
There are thousands of `INFO` and `DEBUG` log lines being logged into syslog every minute, this is making syslog rather unusable. 
I believe these logs are coming from the scrapy processes, they're reporting in as `ocdskingfisher.checks`, `ocdskingfisher.redis-queue`, `ocdskingfisher.web`.

Scrapyd has a logs directory defined [here](https://github.com/open-contracting/deploy/blob/master/salt/kingfisher/collect/files/scrapyd.ini), so that might be a good place to start investigating.

Unless they are needed, we should reduce log output to only warning or above and have these logs stored in their own log file.

**Comment by jpmckinney** [comment]
Aha, I had thought you meant the uwsgi process itself in the email.

We configure this logging in:

* https://github.com/open-contracting/deploy/tree/master/salt/core/rsyslog/files
* logging.json files in https://github.com/open-contracting/deploy/tree/master/salt/kingfisher

The logs do end up in their own files, ultimately; they just pass through syslog first.

We don't have to pass these through syslog. I wasn't aware of it causing issues.

We then rotate the logs in:

* https://github.com/open-contracting/deploy/tree/master/salt/core/logrotate/files

The latter use `postrotate /usr/lib/rsyslog/rsyslog-rotate`, which would have to change if we stop using syslog.

What do you suggest?

**Comment by RobHooper** [comment]
Ah sorry for the confusion - I hadn't worked out where the logs were coming from when mentioned it before, they looked pythonic so thought uWSGI.

We should be able to fix this in `rsyslogd` and keep things working as they are.

I need to test it but the fix might be as simple as stopping rsyslogd once its matched a log file.
Ala: 
> local7.*        /var/log/kingfisher.log & stop

**Comment by jpmckinney** [comment]
Ah, nice one. We can also add a note about using `& stop` here: https://ocdsdeploy.readthedocs.io/en/latest/develop/update/logs.html

**Comment by jpmckinney** [comment]
This will go away when we deploy the new version of kingfisher-process, which uses Docker and so doesn't wrote to the host's log files.
