### ISSUE TITLE
kingfisher-collect: Deploy

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#268]
* [x] Need libpq-dev for psycopg2 to compile
* [x] Create the database and schema to use
* [x] Set KINGFISHER_COLLECT_DATABASE_URL environment variable when adding cron job

Some cleanup:

* [x] Drop business_intelligence_tmp user
* [x] Drop and re-create rbcgroup user

**Comment by jpmckinney** [comment]
@yolile What do you think of using a separate ocdskingfishercollect DB?

The tables don't need to be in the same DB as Kingfisher Process.

**Comment by yolile** [comment]
@jpmckinney I'm ok with having a separate database

**Comment by jpmckinney** [comment]
Done in da7fdd7. I'm doing the first run manually.

**Comment by jpmckinney** [comment]
I forgot to start a tmux. We’ll just check on Monday to see if it worked.
