### ISSUE TITLE
Postgres: Per-query resource contraints

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#272]
For example: automatically stop a query if: it is active for too long, it is using more than 1TB, etc.

Queries started in Google Colaboratory are not killed, so a bad query could get out of hand (as occurred recently).

These limits are relevant on the replica.

**Comment by RobHooper** [comment]
We should be able to achieve this with the [temp_file_limit setting](https://www.postgresql.org/docs/13/runtime-config-resource.html#GUC-TEMP-FILE-LIMIT).
Limiting temp tables to 1TB like so: `temp_file_limit = 1074000000`

**Comment by jpmckinney** [comment]
Awesome - let's do that :)
