### ISSUE TITLE
Use Prometheus for monitoring

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#28]
We would like to switch to Prometheus for OCP server and service monitoring. This is a very popular fully open source project that we now use on our servers - see https://prometheus.io/

Its model is that a small agent runs on the target as a service and makes a HTTP end point available. The Server component then regularly “pulls” data from that end point. The HTTP end point returns a plain text file with a bunch of keys; keys can be fully defined by you.  (This contrasts to a “push” model that others use, tho you can do “push” stuff if you really want.) 

Data is then available in a nice web UI, with current status, historical graphs and alarms. Other dashboards can be hooked up if you want.

The machine exporter ( https://github.com/prometheus/node_exporter ) exports stats such as CPU, RAM and Disk use. Historical data on this lets us answer questions about how much load a machine typically has - these questions have come up before in server planning. We set this up under its own user on each server and in our experience it consumes minimal resources.

We also use https://github.com/prometheus/blackbox_exporter - this lets you monitor websites for good service. (I know we have uptimerobot but a little more doesn’t hurt)

We haven’t used these agents before, but https://prometheus.io/docs/instrumenting/exporters/ lists agents for both Redis and Postgres - good for Kingfisher.

The pull rather than push model makes for a much simpler setup. You can even have more than one server at a time pull data from an end point. This would allow us to setup all the monitors and alerts in ODSC’s infrastructure for now, but if OCP ever wanted the data to appear in their own server later this would be easy to do. It also allows you to run a server on your laptop to test things, but still pull real data - quite nice.

You can write custom exporters, because the HTTP end point format is so simple. They even provide an official Python library so you can easily measure metrics inside your app. https://prometheus.io/docs/instrumenting/clientlibs/ We could use this in things like Kingfisher; monitoring the length of any queues for instance, or monitoring views’ progress.

All configuration is done by files on disk, mostly YAML. This means that salt can simply, immediately and with no human intervention set up a fully working system. (This contrasts nicely to our current system, where salt installs some stuff but then you have to go on by hand to set up the machine in the monitoring network with some awkward steps)

We’d do the basics initially and then talk with you to see what else we wanted to add once it's up and running - but first we wanted to check in quickly to see what you thought of Prometheus?

**Comment by jpmckinney** [comment]
Sounds good! Would OCP have access to the monitors, alerts, etc. on ODSC's Prometheus server? If not, then we should set up a server for OCP.

**Comment by odscjames** [comment]
Basic monitoring has been setup on all 9 servers.

> Would OCP have access to the monitors, alerts, etc. on ODSC's Prometheus server?

Unfortunately there is no way to do that without giving access to other servers data, it's an all or nothing user access model to the server. 

I will make some issues to follow up, including one for OCP's own server.
