### ISSUE TITLE
Add configuration for Registry

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#284]
* [x] All the files are in the /data/deploy on amy01.
* [x] Links to secret gists in this issue: https://github.com/open-contracting/deploy-pillar-private/issues/9

**Comment by jpmckinney** [comment]
grepping .bash_history and .zsh_history in /home/datlab, and ~root/.bash_history, manually installed packages include:

* ufw (I think this can be removed)
* zip (I'm not sure if this is needed)

Web server-related:

* apache2
* certbot

Container-related:

* containerd.io
* docker-ce
* docker-ce-cli
* docker-compose

Database-related:

* postgresql
* postgresql-13
* postgresql-client
* postgresql-client-13
* postgresql-contrib

Programming language-related:

* nodejs
* pip
* python
* python-pip
* python2
* python3
* python3-certbot-apache
* python3-pip
* python3-venv
* scrapyd

Can be installed by Salt if enabled:

* smartmontools

Would be/Were installed by Salt:

* git (core/init)
* htop (core/customization)
* iotop (core/customization)
* tmux (core/customization)
* unzip (core/customization)
* vim (core/customization)
* lm-sensors (maintenance/hardware_sensors)
* wget (maintenance/rkhunter)

The following were already installed with the OS:

* bash-completion

I've purged:

* ack (use grep)
* awscli (not used)
* byobu (use tmux)
* mc (use vim)
* screen (use tmux)
* zsh (use bash)

ack-grep was also installed, but it is not a real package.

**Comment by jpmckinney** [comment]
Some notes from call with Datlab:

* [ ] Need to control log size e.g. via Docker configuration. While we *could* write logs to the main disk and use logrotate, doing so will make it hard to read the logs, as multiple workers will write to the same file.
* [ ] Configure Rabbit outside Docker

Notes from call with Yohanna:

* [ ] Remove volumes from services that don't need/use it
* [ ] Change `network_mode`. The Dockerfile should use regular ports, and then docker-compose can expose them appropriately. (Currently, docker-compose passes a port to gunicorn_runner.sh.)
* [ ] Check whether to change `restart: unless-stopped` to `restart: always`
* [ ] Check how gunicorn, Scrapyd, and the workers handle the stop, etc. signals from Docker
* [ ] Later: Consider whether to use Docker secrets https://docs.docker.com/engine/swarm/secrets/
* [ ] Later: Decide whether to add a frontend for Docker management https://www.portainer.io
* Salt should not run docker-compose. There are many components, not all of which need to be updated on each deploy. Also, if done manually, an administrator can ensure that workers finish or shutdown nicely.

**Comment by jpmckinney** [comment]
Later, when deploying Pelican to the Helpdesk server, need to re-add this service:

```
  vue:
    image: "ghcr.io/open-contracting/pelican-frontend-vue:latest"
    ports:
      - "8004:80"
    restart: unless-stopped
    volumes:
      - /data:/data
```

**Comment by jpmckinney** [comment]
Related issues: https://github.com/open-contracting/data-registry/issues/123

**Comment by jpmckinney** [comment]
My other notes:

* [ ] Configure Salt for Apache, PostgreSQL, RabbitMQ
* [ ] Remove certbot and any related Apache configuration
* [ ] Configure Salt for Kingfisher Collect (re-use existing configuration if possible)
* [ ] Create a new user to run docker compose
* [ ] Review `docker logs` for errors (grep dqt.log for non-info, non-debug, and replace the file with the output)
* [ ] Check Fathom integration (that localhost is excluded, etc.) since Fathom seems to be receiving hits

Cleanup:

* [ ] Remove containers for Kingfisher Collect from GitHub
* [ ] Remove the datlab user from the server, once it's running no processes `find / -type d -not -path '/data/storage/kingfisher-collect/*' \( -user datlab -o -group datlab \)`
* [ ] Document ENV_NAME (used for different Kingfisher Process environments, like testing) and ENV_VERSION (future-proofing, in case the message format changes)
* [ ] Review CI setups across pelican-frontend, pelican-backend, data-registry, kingfisher-collect, kingfisher-process
* [ ] Get registry, pelican, etc. to work in development without having to use `--settings`
* [ ] Eliminate deployment-specific code from individual repositories

**Comment by yolile** [comment]
> Configure Salt for RabbitMQ

I cannot find the config for deploying RabbitMQ anywhere in this repo. And the data registry is using a user that doesn't exist: https://github.com/open-contracting/deploy-pillar-private/blob/f28e1de09ec4c322567cb36e0c5e645cd9abfb9f/registry.sls#L4 so I manually created that user with that password in the server for now

**Comment by yolile** [comment]
We also need to:
- [ ] Run the migrations for pelican-backend somehow
- [ ] Create a superuser for the data_registry the first time

**Comment by jpmckinney** [comment]
> > Configure Salt for RabbitMQ
> 
> I cannot find the config for deploying RabbitMQ anywhere in this repo. And the data registry is using a user that doesn't exist: https://github.com/open-contracting/deploy-pillar-private/blob/f28e1de09ec4c322567cb36e0c5e645cd9abfb9f/registry.sls#L4 so I manually created that user with that password in the server for now. Update: config added here [open-contracting/deploy-pillar-private#17](https://github.com/open-contracting/deploy-pillar-private/pull/17)

The Salt part is https://github.com/open-contracting/deploy/blob/main/salt/rabbitmq/init.sls The Pillar part I had forgotten to commit (with a better username and strong password). I'll make a new PR for the private part.

**Comment by jpmckinney** [comment]
> We also need to:
> 
> * [ ]  Run the migrations for pelican-backend somehow

Can you follow the same pattern as the data registry?

> * [ ]  Create a superuser for the data_registry the first time

Do we need this for Salt or other deployment actions? If not, we typically do this manually.

**Comment by yolile** [comment]
> Can you follow the same pattern as the data registry?

In the data registry, the django migration command is run as a separate container. However, as far as I understand in pelican-backend that command is not used but the migration files are executed directly with `psql` the first time, or maybe I'm missing something?

> Do we need this for Salt or other deployment actions? If not, we typically do this manually.

Ok

**Comment by jpmckinney** [comment]
For the remaining checkbox about pelican-backend's database, I'll do that in https://github.com/open-contracting/deploy/issues/322
