### ISSUE TITLE
Registry: Apache wait for networking

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#286]
I rebooted the Registry server and Apache failed to start on boot.
As you can see in the below log output Apache errors trying to bind to 65.21.93.181, I expect networking isn't completely ready yet on the system. 

> Aug 11 10:16:50 amy01 systemd[1]: Starting The Apache HTTP Server...
> Aug 11 10:16:50 amy01 apachectl[710]: (99)Cannot assign requested address: AH00072: make_sock: could not bind to address 65.21.93.181:80
> Aug 11 10:16:50 amy01 apachectl[710]: no listening sockets available, shutting down
> Aug 11 10:16:50 amy01 apachectl[710]: AH00015: Unable to open logs
> Aug 11 10:16:50 amy01 apachectl[694]: Action 'start' failed.
> Aug 11 10:16:50 amy01 apachectl[694]: The Apache error log may have more information.
> Aug 11 10:16:50 amy01 systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
> Aug 11 10:16:50 amy01 systemd[1]: apache2.service: Failed with result 'exit-code'.
> Aug 11 10:16:50 amy01 systemd[1]: Failed to start The Apache HTTP Server.

We need something to start Apache at the end of the boot process after networking. I think a simple cron running `@reboot` would work but there may be a better way.

**Comment by jpmckinney** [comment]
If I `cat /etc/systemd/system/multi-user.target.wants/apache2.service`

I see:

```
After=network.target remote-fs.target nss-lookup.target
```

`After=network.target` is what we use for Prometheus, Scrapyd, etc.

Is there something more we can do in Apache's service file?
