### ISSUE TITLE
Why are timezone and log_timezone set to 'localtime'

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#291]
I figured it'd be better for all times to be UTC.

Also, Django gets some performance benefit from this being set to UTC, as well as a couple other configurations: https://docs.djangoproject.com/en/3.0/ref/databases/#optimizing-postgresql-s-configuration

**Comment by RobHooper** [comment]
I believe localtime means that postgres uses the C library function `localtime()` in the background and gets the server time - which is UTC.
We should be fine setting this explicitly to UTC as it shouldn't change anything.

**Comment by jpmckinney** [comment]
Aha, seems to be so. I just ran `SELECT localtime` and got the UTC time. `SHOW TimeZone` returns `localtime`, so Django will run a (unnecessary) query to set it to `UTC`. I've added a commit (referencing this issue).

**Comment by jpmckinney** [comment]
Per the linked article, I ran `SHOW client_encoding` (`UTF8`) and `SHOW default_transaction_isolation` (`read committed`), so no other changes are needed.
