### ISSUE TITLE
Add Salt configuration or documentation for additional IP and new disk

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#297]
@RobHooper I don't know if this is the sort of thing that belongs in Salt, or if we just need to document it, as something that only occurs once during the original server build.

**Comment by RobHooper** [comment]
I feel these are one off set-up tasks, custom to the registry server, not suited to salt. I have already documented the additional IP and RAID setup as such in our internal docs. 
I'm not sure if there is a better, shared place we can store one off customisation like this?

That said, regarding networking, we were planning on putting the additional IP in salt #278

**Comment by jpmckinney** [comment]
Ah, I forgot about #278. All good then! Since disks are added rarely (if ever) after initial configuration, I think it's fine to leave in your internal docs. Salt and apps don't need to be aware that some parts of the filesystem are on other disks.
