### ISSUE TITLE
Determine whether to use retain_settings when setting hostname

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#303]
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.network.html#retain-settings

"Use retain_settings to retain current network settings that are not otherwise specified in the state. Particularly useful if only setting the hostname. Default behavior is to delete unspecified network settings."

**Comment by RobHooper** [comment]
Based on this comment in the docs, we should indeed use `retain_settings` however based on this comment https://github.com/open-contracting/deploy/issues/278#issuecomment-924485063_ perhaps we should not be using `network.system` at all, all of our servers are using netplan which `network.system` doesn't work with.

**Comment by jpmckinney** [comment]
I think `network.system` is fine. My reading of Salt's code is that `network.system` just deals with the hostname files, unlike `network.managed` which deals with `/etc/network/interfaces`.

[`network.system`](https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/states/network.py#L755) calls [`apply_network_settings`](https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/debian_ip.py#L1898), which calls [`mod_hostname`](https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/network.py#L1363), which calls `hostnamectl` and edits `/etc/hosts` and `/etc/hostname`.

**Comment by jpmckinney** [comment]
As it turns out, `retain_settings` only affects RedHat, which uses `/etc/sysconfig/network`, and in which there are more settings than just the hostname. I'll add a comment about Salt's confusing docs, and close this issue.
