### ISSUE TITLE
Follow Docker best practices in production

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#307]
Read and consider steps from:

* https://docs.docker.com/compose/production/
* https://docs.docker.com/engine/install/linux-postinstall/
* https://docs.docker.com/engine/security/rootless/

From call with @yolile:

* [x] Remove volumes from services that don't need/use it
* [x] Change `network_mode`. The Dockerfile should use regular ports, and then docker-compose can expose them appropriately. (Currently, docker-compose passes a port to gunicorn_runner.sh.)

----

Steps I don't think we need to take:

* Check whether to change `restart: unless-stopped` to `restart: always`
  * `unless-stopped` is fine. If an admin manually stops a container, it would be annoying for it to restart always.
* Consider whether to use Docker secrets https://docs.docker.com/engine/swarm/secrets/
  * Requires use of Docker swarm, which is too much trouble.

Other notes:

* Salt should not run docker-compose. There are many components, not all of which need to be updated on each deploy. Also, if done manually, an administrator can ensure that workers finish or shutdown nicely.

Note that I already configured log rotation (i.e. setting `log-driver` to `local`).

**Comment by yolile** [comment]
For containers that need access to host services (eg Postgres databases, RabbitMQ, etc) use the same approach as in  https://github.com/open-contracting/deploy/commit/4cf8abb7b450f021eb2ab746e9e002ac9180c111

**Comment by jpmckinney** [comment]
Closing. If we find any other best practices to implement when reviewing docs in #309, we can create new issues.
