### ISSUE TITLE
Set up OCP Prometheus server

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#31]
From #28 

Question 1: Which box should this be on - a new box? A 1GB Bytemark box should be fine.

Question 2: For alerts, we need a way to send email. What shall we use? AWS has an email sending service, or are there other options?

**Comment by jpmckinney** [comment]
I'm fine with a new box.

I can create an AWS SES service. We already using AWS, so simpler than creating a new account with SendGrid, Mailgun, Mandrill, etc., etc.

**Comment by jpmckinney** [comment]
Alternately, if postfix and/or sendmail work, we can just use those.

**Comment by odscjames** [comment]
We have used Postfix before, and it will work IF we get all the anti-spam etc stuff right and depending on which address we are sending to. If your happy with AWS SES that might be more reliable, and given the nature of that that's an important consideration.

I'll make Trello card to allow prioritisation.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up OCP Prometheus server](https://trello.com/c/OcivonLE/118-set-up-ocp-prometheus-server)

**Comment by jpmckinney** [comment]
Sounds good – let me know when ready and I'll set up the service.

**Comment by odscjames** [comment]
Note this task should also include adding documentation on the server.

**Comment by odscjames** [comment]
This has started. New server created at Bytemark.

@jpmckinney  Do you want to set up 2 subdomain aliases for us to use, something like:

* server.prometheus.open-contracting.org
* alerts.prometheus.open-contracting.org

Can you set us up the email service and send on details?

Thanks

ToDo:

* Set up SSL
* Document in docs
* Create public templates of new private files
* Set up email service
* Test an alert

**Comment by jpmckinney** [comment]
Why do we need two subdomains (instead of just e.g. `prometheus.open-contracting.org`)?

**Comment by jpmckinney** [comment]
I added a CNAME from prometheus.open-contracting.org to prometheus.default.opencontracting.uk0.bigv.io, but I'm happy to substitute for the other hostnames once I understand why we'd want to have multiple.

**Comment by jpmckinney** [comment]
I'll need to know which hostname to use to setup SES (DKIM, etc.).

**Comment by odscjames** [comment]
> Why do we need two subdomains (instead of just e.g. prometheus.open-contracting.org)?

There are 2 separate services and thus 2 separate websites. The alerting stuff is actually a separate software component in Prometheus - see separate download in https://prometheus.io/download/ 

> I'll need to know which hostname to use to setup SES (DKIM, etc.).

Which ever you prefer; we can set up SMTP pretty freely and specify any From address. https://prometheus.io/docs/alerting/configuration/#email_config  https://github.com/open-contracting/deploy-salt-private/blob/master/prometheus-server-alertmanager/conf-alertmanager.yml#L12

**Comment by jpmckinney** [comment]
I used:

* monitor.prometheus.open-contracting.org (since every host is a 'server' in a sense)
* alertmanager.prometheus.open-contracting.org (to match the project name)

**Comment by jpmckinney** [comment]
I assume alertmanager doesn't need to receive email, so I haven't configured: 

prometheus.open-contracting.org | MX | 10 inbound-smtp.us-east-1.amazonaws.com

Now waiting for SES to verify the DNS entries I added for its domain and DKIM verification.

**Comment by odscjames** [comment]
Domain names and SSL added.

@jpmckinney Could you edit https://github.com/open-contracting/deploy-salt-private/blob/master/prometheus-server-alertmanager/conf-alertmanager.yml#L12 and put in the from address you configured with AWS? Also, I put in your email address - if you want to change this to your CRM instead please do. The first address is our CRM, please leave that so server staff here get notifications. Then I will deploy and do an test of email sending.

**Comment by jpmckinney** [comment]
notify@prometheus.open-contracting.org is now verified (I had to set up the MX record, then add a Rule Set to store emails sent to that address on S3, in order to verify the email address. I've now removed the MX and Rule Set.)

**Comment by jpmckinney** [comment]
When deploying the changes, can you also remove my email address and add sysadmin@open-contracting.org?

**Comment by odscjames** [comment]
I have changed the email addresses.

**Comment by odscjames** [comment]
I tried an email test and it failed, but our CRM might be having issues at the moment. I will try again soon.

**Comment by jpmckinney** [comment]
Apparently it's because I need to request AWS to move our SES service out of sandbox. Will let you know when that's complete.

**Comment by jpmckinney** [comment]
AWS gave us 50,000 messages per day, and 14 messages per second.

**Comment by odscjames** [comment]
I tried another test. Did you get anything? We didn't. There are no errors in the alert manager log. I can't log into AWS to look for issues there.

**Comment by jpmckinney** [comment]
I can send a test message from the AWS web console.

Aha, it's because the access key and access secret I sent you are for interacting with the AWS APIs. They aren't the SMTP credentials. I've sent the credentials for a 'prometheus-alertmanager' user via WhatsApp.

**Comment by odscjames** [comment]
We got a test email, did you?

Note: Adding --log.level=debug to the start command really helps.

**Comment by jpmckinney** [comment]
Yes, received!

**Comment by jpmckinney** [comment]
I created follow-up issues and added documentation, and did a few other things like adding the service to a spreadsheet that tracks our services, etc. This issue is closed.
