### ISSUE TITLE
Check configuration of Docker networks

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#311]
I checked containers, images, and volumes, but didn't have a change to check the networks (`docker network ls`).

I don't know if they are all still needed, or if any of them need re-configuration.

**Comment by yolile** [comment]
```
deployer@ocp13:~$ docker network ls
NETWORK ID     NAME                    DRIVER    SCOPE
ec010cdcc693   bridge                  bridge    local
069abfffb678   data-registry_default   bridge    local
2eaa6bf31dd4   dqv_default             bridge    local
6617dac33341   host                    host      local
b69388cf74f9   none                    null      local
df712ca5d15e   spoonbill_main          bridge    local
```

We use docker-compose, and docker-compose by default creates the default bridge networks https://docs.docker.com/compose/networking/ when docker-compose up is run. I think we can run `docker network prune`  to get rid of all the unused networks (data-registry_default, dqv_default), and then when we run docker-compose up again all the needed ones will be created.

**Comment by jpmckinney** [comment]
Sounds good to me. If/when we remove `network_mode: "host"`, then I guess we can create network deliberately, and so we won't end up with any extra networks.

**Comment by yolile** [comment]
````
deployer@ocp13:~$ docker network prune
WARNING! This will remove all custom networks not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Networks:
data-registry_default
dqv_default
````

**Comment by yolile** [comment]
> If/when we remove network_mode: "host", then I guess we can create network deliberately, and so we won't end up with any extra networks.

We have removed the network_mode: "host" now. We can create the network deliberately as spoonbill [does](https://github.com/open-contracting/spoonbill-web/blob/cbe6d1e01da8362efd6bf60fd86ffaae093ebd9f/docker-compose.deploy.yaml#L150) or just use the default one created by docker-compose (that have the format: `{service-name}_default`)

**Comment by jpmckinney** [comment]
I think OK to use the default. Spoonbill, in effect, just changes the name from _default to _main.

I added a note about documentation in https://github.com/open-contracting/deploy/issues/309
