### ISSUE TITLE
Pelican: Document how to add collections directly

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/deploy#317]
I would like to be able to add collections to Pelican directly without needing to send an email, so that we can turn around data reviews more quickly.

**Comment by jpmckinney** [comment]
Moving to deploy repo, as this is not an issue in the application.

**Comment by jpmckinney** [comment]
Deployed to pelican.open-contracting.org (using that domain name, as running Pelican every two weeks for most publications on the data registry is too much) and documentation updated.
