### ISSUE TITLE
Prometheus: Add RabbitMQ exporter for Kingfisher

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#32]
From #28 

The agents are at https://prometheus.io/docs/instrumenting/exporters/

**Comment by jpmckinney** [comment]
Of the following, I think only the RabbitMQ exporter is relevant. I'm not sure what the PostgreSQL exporter measures (or what we'd what it to measure).

Queue:

* https://github.com/deadtrickster/prometheus_rabbitmq_exporter#metrics: rabbitmq_node_up, rabbitmq_messages_ready, rabbitmq_messages_unacknowledged, etc. with more details at https://www.rabbitmq.com/prometheus.html#overview-prometheus
* https://github.com/kbudde/rabbitmq_exporter#metrics: up, queue_messages_global, etc. The one above is preferred, as it's mentioned in RabbitMQ's docs.
* https://github.com/oliver006/redis_exporter#whats-exported: We can use `check-keys` to replace Kingfisher's exporter (though with the switch to RabbitMQ we can leave as-is)

SQL:

* https://github.com/wrouesnel/postgres_exporter: No docs on metrics.
* https://github.com/free/sql_exporter: All metrics need to be defined.

Other:

* https://github.com/korfuri/django-prometheus#configuration: Measures latency, though as discussed in https://github.com/open-contracting/deploy/issues/109#issuecomment-603351071 we might prefer something like New Relic.
* https://github.com/igzivkov/tinyproxy_exporter: No docs on metrics.

No especially interesting metrics:

* https://github.com/Lusitaniae/apache_exporter#collectors: We mainly want to know that Apache is up, for which UptimeRobot (or Blackbox Exporter) is sufficient.
* https://github.com/infinityworks/github-exporter/blob/master/METRICS.md: We presently check the number of issues, etc. though a planning process – not a monitoring process.

**Comment by jpmckinney** [comment]
I think the RabbitMQ management interface is sufficient for most of what we want to do with RabbitMQ. This is what the Prometheus integration can do (largely the same): https://www.rabbitmq.com/prometheus.html#overview-example

I think we just want to check that the service is up. That said, we'll see errors in Sentry if it's down. So, for now, I think we can just not monitor RabbitMQ via Prometheus.

**Comment by jpmckinney** [comment]
If this is picked up, see the "Monitoring (deploy)" heading in https://github.com/open-contracting/software-development-handbook/issues/177#issuecomment-5528615337 and `deploy` repo patch in https://github.com/open-contracting/software-development-handbook/issues/177#issuecomment-5528615587
