### ISSUE TITLE
Ensure there is a non-root user on the host to match the uid/gid from the container

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#320]
Processes in containers should not run as root, instead we should be creating a user and running `gunicorn` / `python` as this user.

This will improve system security by reducing python's access, see also [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

We were alerted about from our rootkit monitoring script.

**Comment by jpmckinney** [comment]
Hi @RobHooper, @yolile shared this article with me: https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf

Should we be using the `user:` configuration in docker-compose.yaml files? https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources

Another option is to set a specific UID in the Dockerfile, and to then ensure in the host's configuration that this UID is either not used or that it matches a desired user.

To guarantee that it is not used, I think some Dockerfile's set a very large UID, but then I figure that you need to be careful that different Dockerfiles don't choose the same UID.

What approach do you recommend?

**Comment by RobHooper** [comment]
We recommend ensuring there is a matching user on the system.
Without a user we will end up with files on the system with unclaimed UID/GID's these files are potentially easier for attackers to compromise.

**Comment by jpmckinney** [comment]
I've renamed the issue. We now have all containers running as non-root users, but we still need to ensure the host has a user to match that uid/gid.
