### ISSUE TITLE
Is ocds-legacy site needed any more?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#34]
We tried to move this to ocds-docs-live server, but something hadn't gone totally right as when we decommissioned an old server today  http://ocds.opendataservices.coop/standard/r/1__0__RC/en/standard/intro/  went offline.

But a message was received saying that's not an important site any more? Is that right?

If so, we can remove ocds-legacy from deploy repository to keep things clean.

If not, we should be able to put it back online.

**Comment by jpmckinney** [comment]
I don't know that anything links to `ocds.opendataservices.coop`.

https://standard.open-contracting.org/legacy/r/1__0__RC/en/ and http://ocds.open-contracting.org/opendatacomparison/ both still work.

I think we still want the redirects in https://github.com/open-contracting/deploy/blob/master/salt/apache/ocds-legacy.conf

So, I think there is nothing to do here?
