### ISSUE TITLE
Replace occurrences of old names of products, when deploying to new server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#35]
'ocdskit-web' will become confusing over time, as we (and new users) will forget that it was the old name for Toucan.

**Comment by odscjames** [comment]
Is that https://github.com/open-contracting/deploy/blob/master/salt-config/roster#L13 ?

In fairness we could probably rename most of those machine names :-) They are only used internally by salt. Need to be careful tho, to make sure right variables are still applied.

**Comment by jpmckinney** [comment]
'ocdskit-web' also occurs in filenames and in other files. It'll be less confusing in future if we use Toucan consistently across all repos, documentation, etc.

The other machine names at least roughly correspond to FQDNs, so they are not going to be confusing in the same way.

**Comment by odscjames** [comment]
Fair point. When doing this we'll have to be a bit careful; if you just change the salt rule to install a Apache config called "toucan" instead of "webkit", say, it won't automatically remove the old one - so you'll end up with 2 Apache configs, and so on. Might be a bit of downtime, just 5 mins or so. All doable tho; prioritise away.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toucan: Rename some ocdskit-web occurrences  in deploy repository](https://trello.com/c/MZSCy5kj/123-toucan-rename-some-ocdskit-web-occurrences-in-deploy-repository)

**Comment by jpmckinney** [comment]
As part of this we can start documenting what types of Salt configuration changes require removing earlier configurations (e.g. renaming configuration files).

**Comment by jpmckinney** [comment]
There are now only 3 occurrences in `toucan_pillar.sls` and `toucan.sls`. Changing those are lower priority.

**Comment by jpmckinney** [comment]
Similarly, there are a few occurrences of `scrape` instead of `collect` viz. Kingfisher Collect.

**Comment by jpmckinney** [comment]
Toucan will be decommissioned, so that is no longer an issue.

Once the new flattening tool is deployed, Toucan will just be a web interface to OCDS Kit. However, web analytics show very low usage (low tens of users per month, mostly from Paraguay, the UK and Canada, which is where our teams work). To free up time and resources for more impactful work, Toucan will therefore be decommissioned. People who can’t install OCDS Kit locally will be referred to the OCDS Kit tutorial notebook, and Flatten Tool users will be directed to the new flattening tool.

**Comment by jpmckinney** [comment]
> Similarly, there are a few occurrences of scrape instead of collect viz. Kingfisher Collect.

The helpdesk deployment of Collect is expected to last a while (at least until we upgrade the OS), and it's not worth the effort to get everyone to change their log-in info, so I'll close this issue. We'll likely/hopefully notice the possible renaming when re-deploying.
