### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/deploy#350]
**Full name:** Jen Harris

**Email address:** jen.harris@opendataservices.coop

**What data do you need access to?**

* [ * ] Kingfisher Process
* [ * ] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data?** 
N/A -- New Open Data Services OCDS Helpdesk Analyst

**Comment by yolile** [comment]
closed by https://github.com/open-contracting/deploy-pillar-private/commit/713329e284e513d9a5325893120ff4e21405c8ab
