### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by rorads** [open-contracting/deploy#377]
**Full name:** Rory Scott

**Email address:** rory.scott@paconsulting.com

**What data do you need access to?**

* [x] Kingfisher Process
* [x] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data?** I would like to build a dashboard summarizing the UK public services analytics and data market. This will be used internally within my organisation initially, but I intend to open source and publish the results if it leads to a useful tool.

Also, Hi Yohanna!

**Comment by rorads** [comment]
(I'm not sure if this is a legitimate request, so no worries if I need to go the long way around and self-host, but it would definitely save me some time to use the existing database)

**Comment by rorads** [comment]
I'll be doing backward-looking analysis to begin with, so I think that should be fine. Thank you!

**Comment by yolile** [comment]
Great, I've sent you your credentials by email
