### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by meikevangin** [open-contracting/deploy#378]
Meike van Ginneken

Meikevg@hotmail.com

I would like to request access to data
*Kingfisher Process
*Kingfisher Summarize

I would like to request data because I am looking into doing a consultancy for the Water Integrity Network on cost overruns and corruption. I would like to see if OCP data are useful for this task.

Best regards,

Meike

**Comment by yolile** [comment]
Replied over email
