### ISSUE TITLE
Install flatten tool and ocdskit from PyPi, not GitHub

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#38]
I think we should be PR’ing changes to this repo.

**Comment by odscjames** [comment]
> I think we should be PR’ing changes to this repo.

Noting issue https://github.com/open-contracting/deploy/issues/14 covers this and pull request #40 adds documentation on this - can we move discussion to that issue?

We will look at the title  - "Install flatten tool and ocdskit from PyPi, not GitHub" - in this issue

**Comment by odscjames** [comment]
"Install flatten tool and ocdskit from PyPi, not GitHub" - Now done

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install tools on Kingfisher server](https://trello.com/c/51HD7wKH/128-install-tools-on-kingfisher-server)
