### ISSUE TITLE
Redash is not sending emails

### ISSUE THREAD

**Issue by yolile** [open-contracting/deploy#380]
I created a new account and no email was sent to the new user.
I tried sending an email to reset a user password, but no email was sent.

Maybe related to [#5266](https://github.com/getredash/redash/issues/5266)

**Comment by jpmckinney** [comment]
I've now set `REDASH_SERVER_NAME` as described in that issue. That said, I was getting emails both before and after restarting the container.

**Comment by jpmckinney** [comment]
Note that we already have a worker for the `emails` queue (mentioned in this other issue: https://github.com/getredash/redash/issues/5640)

**Comment by yolile** [comment]
And now Camila also received the password reset email, thanks!

**Comment by jpmckinney** [comment]
It's also possible that `redash_worker_1` had failed and didn't restart properly. Next time I should run `docker ps` before making any changes.
