### ISSUE TITLE
Upgrade servers to Ubuntu 22.04

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#381]
Ubuntu 22.04 is available on Linode.
I am not expecting many changes to our Salt code as it is quite similar to 20.04. We will need to update documentation for the new version.

Currently there are bugs in SaltStack preventing deployments to 22.04 servers, these need resolving before we can move forward with upgrades.
This bug in-particular completely breaks our use of pkgrepo, https://github.com/saltstack/salt/issues/59065

This will supersede the 20.04 server upgrades #145

Change the Ubuntu and Python #346 versions in GitHub Actions workflows:

* [ ] kingfisher-collect
* [ ] kingfisher-process
* [ ] kingfisher-summarize

**Comment by jpmckinney** [comment]
There are PRs for our blocking issues:

* https://github.com/saltstack/salt/pull/63157 for https://github.com/saltstack/salt/issues/59065 (pkgrepo)
* https://github.com/saltstack/salt/pull/63184 for https://github.com/saltstack/salt/issues/60003, which was keeping us locked to salt-ssh<3003

According to the [3005 release notes](https://docs.saltproject.io/en/latest/topics/releases/3005.html) (Aug 2022), Ubuntu 22.04 is supported.

Note that Salt is changing to a ["one-dir"](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#what-is-onedir) packaging approach for future releases.

Also, if using macOS, new versions of salt-ssh require Python 3.9 or 3.10.

**Comment by jpmckinney** [comment]
Okay, I succeeded in upgrading Salt in requirements.txt so that I can use it locally on Python 3.10, macOS Ventura.

I don't have an Ubuntu 22.04 server to test on. I was able to deploy to 18.04 and 20.04 servers using PPAs and filerefs.

**Comment by jpmckinney** [comment]
Noting that I referenced a couple issues in specific applications that will be unblocked by this issue.

**Comment by jpmckinney** [comment]
It looks like we already updated relevant documentation.

Since we've been deploying to Ubuntu 22, it seems the above issues are no longer blockers.

I've moved the Ubuntu and Python changes in project workflows to #402.
