### ISSUE TITLE
Digital Ocean support

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#382]
Support deploying to Digital Ocean

- [ ] Updates to `core` install for new ISP customisation (potentially)
- [ ] Review IPv6 support and configuration
- [ ] Test deployment
- [ ] Update create server documentation

Split from  https://github.com/open-contracting/deploy/issues/145#issuecomment-1227039647

**Comment by jpmckinney** [comment]
I think we're satisfied with Linode and AWS, so closing this issue.
