### ISSUE TITLE
Elasticsearch: Use PEM files instead of Keystore

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#387]
In the new version of ReadOnlyREST (1.44), we can now use PEM files directly: https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#pem-files-instead-of-a-keystore-andor-truststore

This implies deleting:

* [x] pem-to-keystore-wrapper.sh
* [x] pem-to-keystore.sh (probably still need to restart ES though)
* [x] sudoers.d/pem-to-keystore (assuming www-data can be given permission to restart ES via `service` command)
* [x] Related lines in readonlyrest.sls

And changing:

* [x] Related keys in `readonlyrest-docs.yml`
* [x] MDNotifyCmd in `docs.sls`
* [x] Docs in `elasticsearch.rst`

**Comment by RobHooper** [comment]
@jpmckinney , this change has been deployed, ES ROR is now using pem files.
However I have found an issue with this approach, ES cannot load the files directly from Apache due to permissions issues.
I've put a temporary solution in place (copying the cert files to a different path).

We could write a script to automatically copy these files - I am worried this might not work, we had a number of issues with the keystore script.
I think a better solution is to proxy traffic through Apache, removing the SSL configuration from ROR.

**Comment by jpmckinney** [comment]
We can proxy, but I assume the URL/port to access ES will change, so I'll need to update all the sites on the server.

What is the specific permission issue? Can we not change the group/permissions on the original files?

**Comment by jpmckinney** [comment]
Ah, so the files are owned by root and set to 600. The main Apache process runs as root, and then it drops privileges by creating child processes running as www-data. This approach is also what the mod_md maintainers expect of other software: https://github.com/icing/mod_md/issues/84

I haven't checked, but I think ES doesn't take this approach.

> when Apache is restarted

Yes, this seems to be the case based on above issue, so we can't use the same paths/files.

> permissions would reset frequently whenever the cert is renewed

This isn't an issue, since we already have `MDNotifyCmd` at renewal, which can modify the certs.

Can we edit the MDNotifyCmd script to copy the certs and allow only ES to read those copies?

**Comment by jpmckinney** [comment]
We had bugs, but they are solved now: it was because Apache couldn't run the script, and we fixed it by setting up sudoers.

Anyway, sounds good to update the command and leave the proxy as a new issue.

**Comment by jpmckinney** [comment]
> I'll update the MDNotifyCmd script to copy SSL certificate files to another path under this issue.

@RobHooper I think this is the last step before closing this issue.
