### ISSUE TITLE
MySQL backups

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#389]
Old documentation:

> A Dogsbody script at /home/sysadmin-tools/bin/mysql_backup_to_gcloud.sh uploads the Redmine database and files to [Google Cloud](https://console.cloud.google.com/storage/browser?project=ocds-172716&organizationId=1015889055088&folder) under the data@open-contracting.org account. This stores 7 daily backups and 5 weekly backups.

We don't use GCP for anything else, so ideally we would switch to AWS.

Once we do that, we can:

* [ ] Delete the above script from the repository
* [ ] Delete the related GCP project

**Comment by jpmckinney** [comment]
I've now deleted the GCP project.

**Comment by RobHooper** [comment]
I've archived the legacy sysadmin-tools repository (containing mysql_backup_to_gcloud.sh) now that ocp0 is turned off.
