### ISSUE TITLE
Testing Salt changes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#39]
Document how to test changes to Salt against a virtual machine and in a separate branch, perhaps through a simple worked example.

**Comment by robredpath** [comment]
@jpmckinney is this something you'd like our input on?

**Comment by odscjames** [comment]
I have done before and can write up something if wanted, after #40 is merged

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy: Testing changes documentation](https://trello.com/c/g5OBidYI/131-deploy-testing-changes-documentation)

**Comment by jpmckinney** [comment]
Yes! I added a card now.

**Comment by jpmckinney** [comment]
Done in #84
