### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by AnatolPoiata** [open-contracting/deploy#390]
**Full name:** Anatolie Poiata

**Email address:** anatol.poiata@act-tech.com

**What data do you need access to?**

* [X] Kingfisher Process
* [ ] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data?** Research purpose

**Comment by yolile** [comment]
Hello @AnatolPoiata,  I would like to know more about the use you will give the data if possible. Also, I want to share that OCP recently soft-launched the demo version of our "Data Registry" tool, where you can find direct access to all the OCDS implementations; please look at it here: https://data.open-contracting.org/.

**Comment by yolile** [comment]
Closing as unresponsive (and the email doesn't work)
