### ISSUE TITLE
Report user (Redmine) in MySQL isn't configured for IPv6

### ISSUE THREAD

**Issue by dogsbody-ashley** [open-contracting/deploy#393]
No connection through port forwarding prompted investigation. 
Redmine user created for use with IPv6:
```
CREATE USER 'report@'::1' IDENTIFIED BY '<password>'; 
GRANT SELECT ON redmine.* TO 'report'@'::1';
GRANT ALL PRIVILEGES ON *.* TO 'report'@'::1';
FLUSH PRIVILEGES;
```

This needs to be added to Salt.

**Comment by jpmckinney** [comment]
Closing as we don't expect to re-deploy the CRM (it will be decommissioned eventually).
