### ISSUE TITLE
cove-ocds-live-tests broken

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#394]
https://github.com/open-contracting/deploy/actions/runs/3544360947/jobs/5951557544

    Version 3.6 was not found in the local cache
    Error: Version 3.6 with arch x64 not found

The default Ubuntu runner is currently upgrading to the next one and that doesn't have 3.6 in.

A quick fix is adding:

    runs-on: ubuntu-20.04

**Comment by jpmckinney** [comment]
Just made that fix (but trying ubuntu-22.04 first).

Not sure why it only started yesterday.

**Comment by jpmckinney** [comment]
I can confirm that ubuntu-22.04 yields the same result as ubuntu-latest, so using 20.04 now.
