### ISSUE TITLE
Retire Toucan

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#398]
Looking ahead to OCDS 1.2 and next year’s roadmap, I’m thinking of taking Toucan offline. It gets a few dozen visitors per month, so it is not helping a lot of people. For users who can’t install OCDS Kit on their machines, our OCDS Kit Tutorial allows them to run it in a notebook: https://www.open-contracting.org/resources/ocds-kit-tutorial/ For flattening, Toucan will be replaced by https://github.com/open-contracting/spoonbill-web

From https://ocdsdeploy.readthedocs.io/en/latest/deploy/delete_server.html

- ~~If appropriate, notify relevant users of the change~~
- [x] Remove the server from salt/prometheus/server/files/config/conf-prometheus.yml
- [x] [Deploy](https://ocdsdeploy.readthedocs.io/en/latest/deploy/deploy.html) the Prometheus service
- [x] Shutdown the server via the [host](https://ocdsdeploy.readthedocs.io/en/latest/reference/index.html#hosting)’s interface
- [x] Remove all occurrences of the server’s FQDN and IP address from this repository

If the service is being retired:

- [x] Remove its configuration from this repository
- [x] Remove its DNS entries from [GoDaddy](https://dcc.godaddy.com/manage/OPEN-CONTRACTING.ORG/dns)
- [x] Remove its error monitor from [Sentry](https://sentry.io/organizations/open-contracting-partnership/projects/)
- [x] Remove its web analytics from [Fathom Analytics](https://app.usefathom.com/)
- [x] [Remove its project from Google Cloud Platform](https://console.cloud.google.com/cloud-resource-manager?previousPage=%2Fwelcome%3Fproject%3Dtoucan-277800&organizationId=1015889055088), if used
- ~~Remove its resources from Amazon Web Services, if used~~
- [x] Archive its repository on [GitHub](https://ocp-software-handbook.readthedocs.io/en/latest/github/index.html#archival)
- [x] Archive its row in the [Health of software products and services](https://docs.google.com/spreadsheets/d/1MMqid2qDto_9-MLD_qDppsqkQy_6OP-Uo-9dCgoxjSg/edit#gid=1480832278) spreadsheet
- [x] Remove its [managed passwords](https://www.lastpass.com/), if appropriate

Finally:

- [x] Cancel the server via the host’s interface

**Comment by jpmckinney** [comment]
> It gets a few dozen visitors per month

It got 77 visitors in 2022, of which only 4 access a tool (to-json, to-spreadsheet, mapping-sheet).

**Comment by jpmckinney** [comment]
All done. Just going to replace a couple links in the OCDS docs.

**Comment by yolile** [comment]
And we need to delete this learning lab https://www.open-contracting.org/es/resources/learning-lab-using-the-flatten-tool/

**Comment by jpmckinney** [comment]
Good catch. Gone now.
