### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by Narwhaler** [open-contracting/deploy#401]
**Elizabeth Kleban:** 

**ekleban@microsoft.com:** 

**Our team is interested in accessing the OCP kingfisher dataset so that we can use it for testing purposes. We are building a beneficial ownership work and would like to test it with Open Contracting Data for the main goal of building transparency capabilities to help governments detect and prevent risky players.  Results will not be shared. There will be a few requests from my team coming your way. **

* [yes ] Kingfisher Process
* [ yes ] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data?** Please see above. Also, please email me if you have any further questions or would like to discuss further. 
Thanks, 
Elizabeth Kleban
ekleban@microsoft.com

**Comment by jpmckinney** [comment]
Hi Elizabeth, Lindsey responded via email to share the registry, which might be more what you're after.

The [data registry](https://data.open-contracting.org) uses the Kingfisher software to continuously collect all available OCDS data.

We also use Kingfisher for our internal operations. We set up this form before launching the registry, when at the time it was the best available aggregation of OCDS data.
