### ISSUE TITLE
Add external firewall to registry server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#403]
Presently, it just changes the port.

**Comment by RobHooper** [comment]
We cannot set up port-knocking on registry because it is running Docker. 
As you know, the firewall tooling and Docker daemon iptables rules clash preventing us from running both.

We should have a firewall configured in the ISP securing this server instead.

**Comment by jpmckinney** [comment]
Oh, right! Yes, let's do the firewall.

**Comment by jpmckinney** [comment]
At any rate, should we change the SSH port back to 22?

**Comment by RobHooper** [comment]
Confirming the Hardware Firewall was configured back in July 2021.

I don't see any value in changing the SSH port, it isn't causing any problems. 
When the server is eventually rebuilt it will fall in line with the other instances.
