### ISSUE TITLE
Merge downtime protocol into documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#405]
https://docs.google.com/document/d/1qAoh2scU5ZMGC_WYFjjNNJU-34NzYaC4V2xjmb2G75k/edit

Linked from `docs/reference/index.rst`

Not sure if still entirely relevant, cc @RobHooper

**Comment by RobHooper** [comment]
We are still working to this standard - and will continue to do so if you're happy with it.
One change since this document was made is that kingfisher-status@ no longer exists.

**Comment by jpmckinney** [comment]
Thanks - merged into docs in 2fd8de0. Old doc links to https://ocdsdeploy.readthedocs.io/en/latest/reference/downtime.html
