### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by ianistra** [open-contracting/deploy#408]
**Full name:** Ben Moody 

**Email address:** bendavidmoody@protonmail.com

**What data do you need access to?** Australian data from 2016 to present

* [ ] Kingfisher Process
* [ x] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data?** I am supporting a journalistic investigation into links between contracted firms and members of parliament. Having access to an existing database would significantly streamline my efforts.

**Comment by yolile** [comment]
Hi Ben, we recently launched a beta tool, the Data Registry, to access OCDS data over the world, including Australia. Could you check if https://data.open-contracting.org/es/publication/19 or https://data.open-contracting.org/es/publication/11 will be helpful for you? You can download the data directly from them in JSON, Excel, or CSV formats and by year.  Please let me know if that helps.

**Comment by yolile** [comment]
Closing as non-responsive
