### ISSUE TITLE
Kingfisher personal SQL user account

### ISSUE THREAD

**Issue by andrea-fig** [open-contracting/deploy#414]
**Full name: Andrea Frizzmore** 

**Email address: safm.94@hotmail.com** 

**What data do you need access to? Minimum permissible submission periods, e-procurement availability, market dominance indicators in biomedical companies**

* [x] Kingfisher Process
* [x] Kingfisher Summarize

**If you do not work at/with OCP, why do you need access to this data? Study on comparison between countries' public procurement practices and health care services.**

**Comment by yolile** [comment]
Hi @andrea-fig, we recently launched the Data Registry, a tool to access OCDS data over the world. You can download the data directly from them in JSON, Excel, or CSV formats and by year. Please let me know if that helps.

**Comment by jpmckinney** [comment]
*Available at https://data.open-contracting.org

**Comment by yolile** [comment]
Closing as no-responsive
