### ISSUE TITLE
Use ed25519 or rsa for SSH keys

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#423]
Our documentation uses the RSA type with 4096 bits.

I notice that GitHub recommends ed25519 https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

@RobHooper Should we change our docs to use ed25519 going forward?

I think it's fine to leave existing keys as-is.

**Comment by RobHooper** [comment]
Happy to move to ed25519 in the future but we need to test compatibility before we make the jump.
RSA is widely supported but some of the newer algorithms can lag behind especially on older systems.

Scoping out where this is in use:
* Users connecting to servers
* Deploying content from GitHub
Is there anywhere else we need to test?

**Comment by jpmckinney** [comment]
We generate RSA keys for PostgreSQL replication as well.

We also generate RSA key/certs for Prometheus.

That said, I did a little reading and both are equally secure. ed25519 is a little faster, which might matter if you're creating thousands of connections, but we establish connections rarely.

So, I'm also fine with a conclusion that it's not worth switching.

**Comment by jpmckinney** [comment]
Okay, will not switch unless we find a reason to.
