### ISSUE TITLE
Add instructions to create_server to add/edit appropriate reverse DNS entries

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#435]
Hetzner automatically sets one for ipv4.

On ocp04, the ipv6 didn't have an entry. Note that you need to click a tiny + icon to see this.

I haven't checked whether Linode has anything similar.

**Comment by RobHooper** [comment]
PTR can be configured in Linode under the "Network" tab, "Edit RDNS".
Forward DNS is needed before RDNS can be configured.

Obviously we need to address Linode IPv6 #409 which may change how this is configured.
