### ISSUE TITLE
Have Docker logs persist across container restarts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#448]

**Comment by RobHooper** [comment]
We will need to configure logging in three places: Docker, Rsyslog and Logrotate.
I have shared some example configs below based on previous work I've done to configure this on other servers.

We can also use Rsyslog to split Docker logs based on the ImageName, this make the logs easier to work with however it will require custom configs into Salt.

/etc/docker/daemon.json
```
  ...
  "log-driver": "syslog",
  "log-opts": {
    "syslog-address": "unixgram:///var/spool/ocp-docker/logging.sock",
    "tag": "ocp-dockerized-{{.ImageName}}"
}}
```

/etc/rsyslog.d/30-docker.conf
```
$AddUnixListenSocket /var/spool/ocp-docker/logging.sock

# Split out kingfisher logs
:syslogtag, contains, "ocp-dockerized-kingfisher-process"		/var/log/custom-docker/kingfisher.log 
& stop

# Catch all
:syslogtag, contains, "ocp-dockerized" 	/var/log/custom-docker/docker.log
& stop
```

**Comment by jpmckinney** [comment]
Sounds good, and to the extent that we can easily split files by image, that'd make things easier.
