### ISSUE TITLE
kingfisher-main Deployment error

### ISSUE THREAD

**Issue by dogsbody-rob** [open-contracting/deploy#455]
Deploying `kingfisher-main` is currently erroring due to uWSGI dependency (see error below).

Looking into this issue a bit, `salt/kingfisher/summarize/init.sls` includes `python_apps`, this file then includes `uwsgi` if it is defined in pillar.
The apps are now hosted in Docker so `uwsgi` is no longer defined.

```
$ ./run.py "kingfisher-main" state.apply test=True
kingfisher-main:
    - Cannot extend ID 'uwsgi' in 'base:python_apps'. It is not part of the high state.
      This is likely due to a missing include statement or an incorrectly typed ID.
      Ensure that a state with an ID of 'uwsgi' is available
      in environment 'base' and to SLS 'python_apps'
```

**Comment by jpmckinney** [comment]
Kingfisher Summarize isn't Dockerized, but it doesn't use uWSGI either.

I had refactored virtualenvs into a macro, but accidentally omitted an if-statement. Fixed now.
