### ISSUE TITLE
Change A records for data and flatten to CNAMEs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#456]
ocp13 now only needs one IP (65.21.93.181) instead of two, so we can point these subdomains to ocp13.open-contracting.org. instead.

**Comment by dogsbody-rob** [comment]
DNS Updated in GoDaddy moving both subdomains to CNAME records.

Noting that as part of this change these records now have AAAA / IPv6 DNS records as this wasn't configured previously.
