### ISSUE TITLE
Decommission 65.21.93.141 for ocp13 from Hetzner

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#457]

**Comment by dogsbody-rob** [comment]
IP removed from server network configs – a36ed7b39f7c1ccf87a46bfebec8927d4f751b19
I cannot see an option to return the IP in the Hetzner interface, it may not be possible.

**Comment by jpmckinney** [comment]
@dogsbody-rob Do we create a support ticket? It's not much, but they do charge for it.

**Comment by dogsbody-rob** [comment]
Currently costing €1.7 per month. 
I will raise a support ticket enquiring.

**Comment by jpmckinney** [comment]
By the way, should [kingfisher_main (ocp23)](https://github.com/open-contracting/deploy/blob/main/pillar/kingfisher_main.sls) have specific netplan configuration, similar to registy (ocp13)?

https://github.com/open-contracting/deploy/blob/65488eb70e58d30d047164aad611271d7d8f8056/pillar/registry.sls#L5-L28

**Comment by dogsbody-rob** [comment]
> By the way, should [kingfisher_main (ocp23)](https://github.com/open-contracting/deploy/blob/main/pillar/kingfisher_main.sls) have specific netplan configuration, similar to registry (ocp13)?

We made the decision to only add networking into Salt when we are changing it, which I still stand by.
ocp23 uses the out-of-the-box Hetzner network configuration.
This should be noted on the networking docs.

Ref – https://github.com/open-contracting/deploy/pull/418#issuecomment-1580835760

**Comment by jpmckinney** [comment]
> This should be noted on the networking docs.

Thanks! I added a small clarification.

**Comment by dogsbody-rob** [comment]
Confirming `65.21.93.141` has been cancelled in Hetzner.
