### ISSUE TITLE
Redmine: Disable data@ email access

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#461]
Marking as blocked as we don't have a practice of checking this inbox, otherwise.

Once Redmine stops checking, we can change Google Admin's ["Less secure apps"](https://admin.google.com/ac/security/lsa) setting.

**Comment by yolile** [comment]
> Marking as blocked as we don't have a practice of checking this inbox, otherwise.

To unblock this one, @jpmckinney could you forward the emails to data@ to my email?

**Comment by jpmckinney** [comment]
I instead renamed data@ to data-archive@ and created a group for data@ that anyone at OCP can join (I made you owner): https://groups.google.com/a/open-contracting.org/g/data

**Comment by jpmckinney** [comment]
I removed the email configuration from Redmine, and I changed the less secure apps setting (I think only Redmine was an "insecure app").
