### ISSUE TITLE
Sentry: Delete open-contracting-standard-coll

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#50]
Nothing reports to it. Its DSN doesn't occur in this repository.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Toucan to sentry.io](https://trello.com/c/XNybTfXS/117-add-toucan-to-sentryio)

**Comment by odscjames** [comment]
I can't find any use of this either. Removed.
