### ISSUE TITLE
gateway4 and gateway6 are deprecated

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#503]
Need to update linode template for netplan.

Deprecated since [0.103](https://github.com/canonical/netplan/releases/tag/0.103) on Aug 4, 2021

Hold off on ocp16 which is still Ubuntu 20.04 #494

**Comment by RobHooper** [comment]
Updated and deployed.
I have also updated ocp16 because Netplan was already on a newer version flagging this deprecation.

https://github.com/open-contracting/deploy/commit/fc80b0cf9aa43fea27bb75d755fbceba4e983379
