### ISSUE TITLE
PostgreSQL 12 End of Life on ocp13

### ISSUE THREAD

**Issue by ghost** [open-contracting/deploy#504]
[PostgreSQL Release Dates](https://www.postgresql.org/support/versioning/)

PostgreSQL 12 is due to go End Of Life on 14th Nov 2024. This affects ocp13 (registry).

It will need to be updated to one of the following versions:
PostgreSQL-13. EOL is 13 Nov 2025
ocp14 is on this version currently. 

PostgreSQL-14. EOL is 12 Nov 2026

PostgreSQL-15. EOL is 11 Nov 2027
ocp22, ocp23 & ocp24 are on this version currently.

**Comment by jpmckinney** [comment]
I think OCP will end up upgrading PostgreSQL when rebuilding the ocp13 server as part of #494
