### ISSUE TITLE
Sentry: Delete open-contracting-validator and add project that corresponds to CoVE DSN's

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#51]
The DSN for open-contracting-validator isn't the same as those in this repo. So, I assume there is another project that is the 'real' one for the OCDS and OC4IDS Data Review Tools.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Toucan to sentry.io](https://trello.com/c/XNybTfXS/117-add-toucan-to-sentryio)

**Comment by odscjames** [comment]
They were set to go into the generic "Cove" project.

I have set up 2 O.C. validator projects, and deployed the correct / new DSN's.
