### ISSUE TITLE
OC4IDS Data Review Tool's language switcher has CSRF error

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#53]
https://standard.open-contracting.org/infrastructure/review/

This doesn't occur with the OCDS DRT: https://standard.open-contracting.org/review/

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OC4IDS Data Review Tool's language switcher has CSRF error](https://trello.com/c/P3SHlwfQ/255-oc4ids-data-review-tools-language-switcher-has-csrf-error)

**Comment by odscjames** [comment]
Also noting that starting at https://standard.open-contracting.org/infrastructure/latest/es/ and clicking the review link takes you to the English version.

**Comment by odscjames** [comment]
> Also noting that starting at https://standard.open-contracting.org/infrastructure/latest/es/ and clicking the review link takes you to the English version.

Same is true of both Cove's - I'll make an issue for that
