### ISSUE TITLE
Can we delete mail-whois.local, uwsgi.conf and references

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#70]
Per https://github.com/OpenDataServices/opendataservices-deploy/commit/09a3cdb72d038748c2cbb3dcc8c690f145248a3b: "Don't do jail for uwsgi, it's broken". Since that code was commented out (and removed in this repo), the two configs in the issue title don't have any effect (as I understand).

**Comment by jpmckinney** [comment]
cc @idlemoor as committer of above.

**Comment by jpmckinney** [comment]
Can close #69 if these can be deleted.

**Comment by idlemoor** [comment]
Morning James, I've spoken to James B about this today and he wants me to handle this and #69. I'm horribly out of practice, but my initial reaction is that yes, this is a Good Thing -- the fact that we're here nearly 3 years later discussing it shows that we'd have been better off removing it more completely in the first place. Thanks for raising this issue. I'll be back later with a commit to do the deed.
