### ISSUE TITLE
Enable permissions UI in Redash

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#78]
See https://github.com/getredash/redash/pull/1113#issuecomment-273708431

I think this just requires setting the `REDASH_FEATURE_SHOW_PERMISSIONS_CONTROL` environment variable to `true`

https://redash.io/help/open-source/admin-guide/env-vars-settings

**Comment by jpmckinney** [comment]
Likely worth doing after #1

**Comment by odscjames** [comment]
Seems good
