### ISSUE TITLE
User can't login to Kingfisher Scrape any more

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#83]
I have a ODSC colleague who now can't log in to Kingfisher Scrape user, but they can still log in as process user.

Need to investigate and see what's happening here

**Comment by odscjames** [comment]
I can't find anything wrong here, I will go back to user

**Comment by duncandewhurst** [comment]
For the avoidance of doubt the user was me and it was definitely user error (trying to ssh in to scrape from a process session...)
