### ISSUE TITLE
Setup PostgreSQL replication server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#86]
We might want to have a second server with a replication database for read-only operations. This would serve:

- Redash
- Pelican
- Colab notebooks

And any other uses of the read-only user.

I don't know that this server would need anything beyond the basics besides PostgreSQL.

The primary server would then be reserved for write operations (Kingfisher Scrape, Kingfisher Process, etc.).  It'd largely be locked down (web interactions only for analysts, no CLI access).

In case of secondary server downtime, we can have instructions for (temporarily) switching to the primary server for read operations.

~~This issue is blocked until we bring our read/write volume down (mainly by not rebuilding all the views every day).~~

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identify + implement mitigations for kingfisher-process downtime](https://trello.com/c/VjGXTBis/150-identify-implement-mitigations-for-kingfisher-process-downtime)

**Comment by jpmckinney** [comment]
Related: #3

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hosted Kingfisher - Set up database replication](https://trello.com/c/YNH8OtT1/217-hosted-kingfisher-set-up-database-replication)

**Comment by jpmckinney** [comment]
If we want to lock down access to the process server, we can perhaps move Kingfisher Views to the replication server. https://github.com/open-contracting/kingfisher-archive/issues/10#issuecomment-527773582

**Comment by jpmckinney** [comment]
Copying notes from Trello card.

In terms of technology:

> We should investigate database-level replication and block-level replication strategies.

In terms of failure procedures:

> There will be procedures in place to handle expected failure scenarios, including catastrophic failure, and more nuanced failure modes.
> We should design appropriate procedures to target no more than 1h of service interruption in the worst case. 
> We should ensure that appropriate pre-authorisation of any foreseeable costs is in place so that we're resilient to not being able to contact OCP staff - eg if one server has failed, another is doing all the work, we may decide that our procedure is to spin up a new server to pre-seed replication on to from the first server....which costs small, predictable amounts of money.

**Comment by RobHooper** [comment]
A new server (kingfisher-replica1) has been built, configured and is now replicating kingfisher-process1. Ref #168.

Regarding failover procedure while data is now being replicated to kingfisher-replica1 it is on the user to query the correct server.
In other words, if kingfisher-process1 breaks we cannot stop users from visiting the broken server.

I think it would be best for us to create new DNS records pointing to these services, for example:
kingfisher-postgres.open-contracting.org -> kingfisher-process1
kingfisher-postgres-ro.open-contracting.org (read only) ->  kingfisher-replica1

In the case that either server failed, we can point both records at the working one reducing the impact on users.

**Comment by RobHooper** [comment]
`postgres.kingfisher` and `replica.kingfisher` work fine - whatever makes the most sense to the user :) 
Maybe a question of semantics, if `replica` is more clear and approachable than `postgres-readonly`. I couldn't say, both work.


Currently MITM SSL alerts isn't an issue and we could point either record at either server but I think this will change when #152 is implemented.

**Comment by jpmckinney** [comment]
Hmm, since we'll have some external users connecting, let's go with `postgres-readonly`.

**Comment by RobHooper** [comment]
Cool, I've set up DNS for ``postgres.kingfisher.open-contracting.org`` and ``postgres-readonly.kingfisher.open-contracting.org``

**Comment by jpmckinney** [comment]
@RobHooper Great! Does that mean I can now inform users about reading from postgres-readonly.kingfisher.open-contracting.org?

**Comment by RobHooper** [comment]
Yes, I'm happy for users to start querying postgres-readonly.
We were already considering it a production server. 

It should probably be added to [the docs](https://ocdsdeploy.readthedocs.io/en/latest/use/databases.html), I'll leave this with you. 

The replica is a total copy of master so it has the same user logins + user changes get replicated.

**Comment by jpmckinney** [comment]
@RobHooper Can this issue now be closed?

**Comment by RobHooper** [comment]
@jpmckinney Just reviewing this issue, there was one comment regarding moving Kingfisher Views to use the replica endpoint.
I'm not sure if this was done? or if there are any other tools we can/should point at the replica?

Other than that, we're good to close this issue.

**Comment by jpmckinney** [comment]
I think we've done all we could.

Kingfisher Views reads from the public schema and writes to new schema. I don't know if there's an option in PostgreSQL to replicate one schema as read-only, then write additional schema. That was the idea, though. However, I think it's better to replicate everything, so that if either server goes down, then users still have access to everything.
