### ISSUE TITLE
Decommission ocdskingfisher-new (95.216.243.15)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#90]
Follow-up to #89

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tidy up after Kingfisher Server move](https://trello.com/c/lWGCgSsU/168-tidy-up-after-kingfisher-server-move)

**Comment by jpmckinney** [comment]
Planned to occur before the next billing date (January 10).

**Comment by robredpath** [comment]
I've set the server to cancel on the 9th.

**Comment by odscjames** [comment]
Server Shutdown and removed from Prometheus.

Notice sent to email list.

Now waiting a few days to make sure no complaints.

TODO: remove entry from salt roster.

**Comment by odscjames** [comment]
I have logged into Hetzner and verified the server is gone.

Removed from salt.

I think that is it - anything else?

**Comment by jpmckinney** [comment]
I think that's all done.
