### ISSUE TITLE
Add ocdskingfisherarchiveonprocess to new server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#91]
Follow-up to #89

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tidy up after Kingfisher Server move](https://trello.com/c/lWGCgSsU/168-tidy-up-after-kingfisher-server-move)

**Comment by odscjames** [comment]
Deployed. Am testing by hand, will leave open and double check cron job in a few days.

**Comment by odscjames** [comment]
Cron run last night looks fine
