### ISSUE TITLE
WAL files are two-thirds of all used disk space

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#93]
@robredpath @odscjames I was surprised to see the server is (as of now) at 90% disk used – considering we doubled the size of the disk.

I determined that `/var/lib/postgresql/11/main/base` and `/var/lib/postgresql/11/main/pg_wal` account for 97% of the used space, with WAL files taking up 2/3 of that.

We are likely causing a massive number of WAL files to be created due to how Views are generated.

Please address the issue so we don't run out of space and cause another server failure.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher: WAL files are two-thirds of all used disk space](https://trello.com/c/xSzo44UX/165-kingfisher-wal-files-are-two-thirds-of-all-used-disk-space)

**Comment by odscjames** [comment]
pg_wal is taking up 2.4T	- unknown as to why.

max_wal_size is set to 1GB. Looking into this.

**Comment by jpmckinney** [comment]
Some things to check: https://stackoverflow.com/questions/35144403/which-postgresql-wal-files-can-i-safely-remove-from-the-wal-archive-folder

**Comment by odscjames** [comment]
WAL Archive is off, keep is 0, can't see any settings that explain this

2 Things to chase up, I Think the first is most likely:

1)

```

postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid |       database        | temporary | active | active_pid | xmin | catalog_xmin |  restart_lsn  | confirmed_flush_lsn 
-----------+----------+-----------+--------+-----------------------+-----------+--------+------------+------+--------------+---------------+---------------------
 backup    | pgoutput | logical   |  16579 | ocdskingfisherprocess | f         | f      |            |      |    293607328 | 8D55/670BAB00 | 8D55/670BAB00
(1 row)

```

This may be making Postgres keep WAL logs - I'm going to look into this next. We have no replication use but it may have been tried as a way of copying data last week?

2) 

The way we rsync datafiles from one server to the other last week may mean that some WAL logs were removed from old sever, left on new server and then postgres doesn't touch them. but 2.4G seems high for that, and I'm not seeing any gap in the timestamps in the WAL, which I would expect to see if this was the cause

**Comment by odscjames** [comment]
I think

    select pg_drop_replication_slot('backup');

Is what we need here but I want to talk to some people here to confirm it, as if it turns out we do have some kind of data replication need (I'm 99% sure we don't) that will break it. Am trying to do that as quickly as possible

**Comment by odscjames** [comment]
/dev/md2        3.8T  1.1T  2.5T  31% /

Leaving open to check any wrap up

**Comment by jpmckinney** [comment]
Great! So was the issue that replication had been turned on last week?

**Comment by odscjames** [comment]
Yes, there was an attempt to use replication to move data between servers and it wasn't turned off afterwards.

**Comment by jpmckinney** [comment]
Closing per discussion on review call.
