### ISSUE TITLE
Python2 vs python3 issue

### ISSUE THREAD

**Issue by robredpath** [open-contracting/deploy#94]
When I try to add a new key to a server (specifically, `kingfisher-process1`) , I got:

```
          ID: analysis_kingfisher_authorized_keys_add
    Function: ssh_auth.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_b290a4_salt/pyall/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/var/tmp/.root_b290a4_salt/pyall/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.root_b290a4_salt/pyall/salt/states/ssh_auth.py", line 317, in present
                  key = key.rstrip().split('\n')
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6164: ordinal not in range(128)
     Started: 19:00:31.471689
    Duration: 1.059 ms
     Changes:
```

I suspected python2 vs 3 issues, and sure enough it worked when I installed salt-ssh into a virtualenv with python3. 

I don't think this is a big deal, and just needs documenting rather than fixing - given the imminent end of Python 2. If others agree (@odscjames @jpmckinney ) I'll just add something to https://ocdsdeploy.readthedocs.io/en/latest/how-to/get_started.html#install-salt

**Comment by robredpath** [comment]
(I was previously using version of salt-ssh installed by apt on Ubuntu 18.04, which apparently brought in python2 with it!)

**Comment by jpmckinney** [comment]
Yes, please add a note about using Python 3 (ideally >= 3.6, as 3.5 is also EOL soon).

**Comment by odscjames** [comment]
>  just needs documenting rather than fixing - given the imminent end of Python 2.

Fully agree, doccing would be great - thanks.
